/* ============================================================
   English Quest — Content Data
   Eiken 5級 → 2級 level vocabulary & sentence patterns
   Edit this file to add/change words, units, or questions.

   NOTE ON SCOPE: this is an expanded version (roughly 3-4x the
   original word counts), extending each category up through
   Eiken Pre-2 / 2 level vocabulary. Reaching 500+ words per
   category is a much larger project intended to continue across
   future editing sessions — see PROJECT_SUMMARY.md.
   ============================================================ */
(function (global) {
  "use strict";

  // ---- Units (themed word groups, Eiken 5級 -> 2級 difficulty) ----
  var UNITS = [
    {
      id: "school",
      name: "School Life",
      emoji: "🏫",
      level: 5,
      words: [
        { en: "student", ja: "生徒" },
        { en: "teacher", ja: "先生" },
        { en: "classroom", ja: "教室" },
        { en: "textbook", ja: "教科書" },
        { en: "notebook", ja: "ノート" },
        { en: "pencil", ja: "鉛筆" },
        { en: "eraser", ja: "消しゴム" },
        { en: "homework", ja: "宿題" },
        { en: "test", ja: "テスト" },
        { en: "library", ja: "図書館" },
        { en: "lunch", ja: "昼食" },
        { en: "friend", ja: "友達" },
        { en: "club", ja: "部活" },
        { en: "subject", ja: "教科" },
        { en: "schedule", ja: "時間割" },
        { en: "principal", ja: "校長先生" },
        { en: "classmate", ja: "クラスメート" },
        { en: "uniform", ja: "制服" },
        { en: "blackboard", ja: "黒板" },
        { en: "chalk", ja: "チョーク" },
        { en: "desk", ja: "机" },
        { en: "chair", ja: "椅子" },
        { en: "gym", ja: "体育館" },
        { en: "playground", ja: "校庭" },
        { en: "exam", ja: "試験" },
        { en: "grade", ja: "学年・成績" },
        { en: "graduation", ja: "卒業" },
        { en: "entrance ceremony", ja: "入学式" },
        { en: "vacation", ja: "休み" },
        { en: "absent", ja: "欠席の" },
        { en: "present (at school)", ja: "出席の" },
        { en: "rule", ja: "規則" },
        { en: "lesson", ja: "授業" },
        { en: "score", ja: "点数" },
        { en: "report card", ja: "通知表" },
        { en: "field trip", ja: "遠足" },
        { en: "school festival", ja: "学園祭" },
        { en: "dormitory", ja: "寮" },
        { en: "scholarship", ja: "奨学金" },
        { en: "curriculum", ja: "カリキュラム" },
        { en: "assignment", ja: "課題" },
        { en: "ruler", ja: "定規" },
        { en: "scissors", ja: "はさみ" },
        { en: "glue", ja: "のり" },
        { en: "backpack", ja: "リュック" },
        { en: "locker", ja: "ロッカー" },
        { en: "hallway", ja: "廊下" },
        { en: "stairs", ja: "階段" },
        { en: "cafeteria", ja: "食堂" },
        { en: "schoolyard", ja: "校庭" },
        { en: "bell", ja: "ベル" },
        { en: "term", ja: "学期" },
        { en: "semester", ja: "学期" },
        { en: "timetable", ja: "時間割" },
        { en: "attendance", ja: "出席" },
        { en: "tardy", ja: "遅刻した" },
        { en: "detention", ja: "居残り" },
        { en: "punishment", ja: "罰" },
        { en: "praise", ja: "褒めること" },
        { en: "achievement", ja: "達成" },
        { en: "ability", ja: "能力" },
        { en: "effort", ja: "努力" },
        { en: "improve", ja: "上達する" },
        { en: "review", ja: "復習する" },
        { en: "preview", ja: "予習する" },
        { en: "memorize", ja: "暗記する" },
        { en: "understand", ja: "理解する" },
        { en: "explain", ja: "説明する" },
        { en: "answer", ja: "答える" },
        { en: "question", ja: "質問" },
        { en: "raise (a hand)", ja: "（手を）挙げる" },
        { en: "discuss", ja: "話し合う" },
        { en: "presentation", ja: "発表" },
        { en: "speech", ja: "スピーチ" },
        { en: "essay", ja: "作文" },
        { en: "composition", ja: "作文" },
        { en: "grammar", ja: "文法" },
        { en: "vocabulary", ja: "語彙" },
        { en: "spelling", ja: "つづり" },
        { en: "pronunciation", ja: "発音" },
        { en: "translate", ja: "翻訳する" },
        { en: "dictionary", ja: "辞書" },
        { en: "calculator", ja: "電卓" },
        { en: "experiment", ja: "実験" },
        { en: "laboratory", ja: "実験室" },
        { en: "microscope", ja: "顕微鏡" },
        { en: "equation", ja: "方程式" },
        { en: "geometry", ja: "幾何学" },
        { en: "history (subject)", ja: "歴史" },
        { en: "geography", ja: "地理" },
        { en: "science", ja: "理科" },
        { en: "mathematics", ja: "数学" },
        { en: "physical education", ja: "体育" },
        { en: "art class", ja: "美術" },
        { en: "music class", ja: "音楽" },
        { en: "moral education", ja: "道徳" },
        { en: "elective", ja: "選択科目" },
        { en: "required course", ja: "必修科目" },
        { en: "credit (academic)", ja: "単位" },
        { en: "diploma", ja: "卒業証書" },
        { en: "certificate", ja: "証明書" },
        { en: "enroll", ja: "入学する" },
        { en: "admission", ja: "入学" },
        { en: "tuition", ja: "授業料" },
        { en: "campus", ja: "キャンパス" },
        { en: "faculty", ja: "教職員" },
        { en: "counselor", ja: "カウンセラー" },
        { en: "nurse's office", ja: "保健室" },
        { en: "PTA", ja: "保護者会" },
        { en: "homeroom", ja: "ホームルーム" },
        { en: "transfer student", ja: "転校生" },
        { en: "exchange student", ja: "交換留学生" },
        { en: "study abroad", ja: "留学する" },
        { en: "self-study", ja: "自習" },
        { en: "cram school", ja: "塾" },
        { en: "tutor", ja: "家庭教師" },
        { en: "academic", ja: "学業の" },
        { en: "diligent", ja: "勤勉な" },
        { en: "lazy", ja: "怠惰な" },
        { en: "cheat (on a test)", ja: "カンニングする" },
        { en: "honest", ja: "正直な" },
        { en: "responsible", ja: "責任感のある" },
        { en: "punctuality", ja: "時間厳守" },
        { en: "cooperation", ja: "協力" },
        { en: "leadership", ja: "リーダーシップ" },
        { en: "committee", ja: "委員会" },
        { en: "representative", ja: "代表" },
        { en: "election (class)", ja: "選挙" },
        { en: "volunteer work", ja: "ボランティア活動" },
        { en: "whiteboard", ja: "ホワイトボード" },
        { en: "gymnasium", ja: "体育館" },
        { en: "auditorium", ja: "講堂" },
        { en: "indoor shoes", ja: "上履き" },
        { en: "outdoor shoes", ja: "外履き" },
        { en: "school anthem", ja: "校歌" },
        { en: "study group", ja: "勉強会" },
        { en: "midterm exam", ja: "中間試験" },
        { en: "final exam", ja: "期末試験" },
        { en: "homework deadline", ja: "宿題の締め切り" },
        { en: "class president", ja: "学級委員長" },
        { en: "school newsletter", ja: "学校だより" },
        { en: "bulletin board", ja: "掲示板" },
        { en: "ID card", ja: "身分証明書" },
        { en: "sports day", ja: "運動会" },
        { en: "homeroom teacher", ja: "担任の先生" },
        { en: "school rules", ja: "校則" },
        { en: "school trip", ja: "修学旅行" },
        { en: "name tag", ja: "名札" },
        { en: "school bag", ja: "通学かばん" },
        { en: "opening ceremony", ja: "始業式" },
        { en: "closing ceremony", ja: "終業式" },
        { en: "after-school activity", ja: "放課後の活動" },
        { en: "study desk", ja: "勉強机" },
        { en: "marker pen", ja: "マーカーペン" },
        { en: "stapler", ja: "ホチキス" },
        { en: "projector", ja: "プロジェクター" },
        { en: "lecture", ja: "講義" },
        { en: "scholarship exam", ja: "奨学金試験" },
        { en: "club activity", ja: "部活動" },
        { en: "after-school tutoring", ja: "放課後の補習" },
        { en: "school uniform shoes", ja: "通学靴" },
        { en: "homework checklist", ja: "宿題チェックリスト" },
        { en: "school cafeteria menu", ja: "学食メニュー" },
        { en: "class schedule chart", ja: "時間割表" },
        { en: "report deadline", ja: "レポートの締め切り" },
        { en: "extra credit", ja: "追加点" },
        { en: "pop quiz", ja: "抜き打ちテスト" },
        { en: "group project", ja: "グループ課題" },
        { en: "study session", ja: "勉強セッション" },
        { en: "class rank", ja: "クラス順位" },
        { en: "academic year", ja: "学年度" },
        { en: "school motto", ja: "校訓" },
        { en: "student council", ja: "生徒会" },
        { en: "yearbook", ja: "卒業アルバム" },
        { en: "graduation speech", ja: "卒業スピーチ" },
        { en: "exam result", ja: "試験結果" },
        { en: "school supplies", ja: "学用品" },
        { en: "pencil case", ja: "筆箱" },
        { en: "class representative", ja: "学級代表" },
        { en: "boarding school", ja: "全寮制学校" },
        { en: "public school", ja: "公立学校" },
        { en: "private school", ja: "私立学校" },
        { en: "co-ed school", ja: "共学校" },
        { en: "all-boys school", ja: "男子校" },
        { en: "all-girls school", ja: "女子校" },
        { en: "make up a class", ja: "授業の埋め合わせをする" }
      ]
    },
    {
      id: "family",
      name: "Family & People",
      emoji: "👨‍👩‍👧‍👦",
      level: 5,
      words: [
        { en: "mother", ja: "母" },
        { en: "father", ja: "父" },
        { en: "sister", ja: "姉・妹" },
        { en: "brother", ja: "兄・弟" },
        { en: "grandmother", ja: "祖母" },
        { en: "grandfather", ja: "祖父" },
        { en: "family", ja: "家族" },
        { en: "baby", ja: "赤ちゃん" },
        { en: "uncle", ja: "おじ" },
        { en: "aunt", ja: "おば" },
        { en: "cousin", ja: "いとこ" },
        { en: "parents", ja: "両親" },
        { en: "husband", ja: "夫" },
        { en: "wife", ja: "妻" },
        { en: "son", ja: "息子" },
        { en: "daughter", ja: "娘" },
        { en: "nephew", ja: "甥" },
        { en: "niece", ja: "姪" },
        { en: "relative", ja: "親戚" },
        { en: "neighbor", ja: "隣人" },
        { en: "stranger", ja: "見知らぬ人" },
        { en: "adult", ja: "大人" },
        { en: "child", ja: "子ども" },
        { en: "elderly", ja: "高齢の" },
        { en: "twin", ja: "双子" },
        { en: "only child", ja: "一人っ子" },
        { en: "single parent", ja: "片親" },
        { en: "guardian", ja: "保護者" },
        { en: "ancestor", ja: "先祖" },
        { en: "generation", ja: "世代" },
        { en: "household", ja: "世帯" },
        { en: "marriage", ja: "結婚" },
        { en: "couple", ja: "夫婦・カップル" },
        { en: "stepfather", ja: "継父" },
        { en: "stepmother", ja: "継母" },
        { en: "infant", ja: "幼児" },
        { en: "toddler", ja: "よちよち歩きの子" },
        { en: "teenager", ja: "10代の若者" },
        { en: "youth", ja: "若者" },
        { en: "newborn", ja: "新生児" },
        { en: "pregnant", ja: "妊娠している" },
        { en: "raise (children)", ja: "育てる" },
        { en: "upbringing", ja: "しつけ" },
        { en: "discipline", ja: "しつけ・規律" },
        { en: "obey", ja: "従う" },
        { en: "spoil (a child)", ja: "甘やかす" },
        { en: "resemble", ja: "似ている" },
        { en: "personality", ja: "性格" },
        { en: "appearance", ja: "外見" },
        { en: "behavior", ja: "行動" },
        { en: "attitude", ja: "態度" },
        { en: "trust", ja: "信頼" },
        { en: "support (verb)", ja: "支える" },
        { en: "rely on", ja: "頼る" },
        { en: "argument", ja: "口論" },
        { en: "reconcile", ja: "仲直りする" },
        { en: "forgive", ja: "許す" },
        { en: "apologize", ja: "謝る" },
        { en: "comfort", ja: "慰める" },
        { en: "encourage", ja: "励ます" },
        { en: "advice", ja: "助言" },
        { en: "role model", ja: "お手本" },
        { en: "inherit", ja: "受け継ぐ" },
        { en: "heritage", ja: "遺産・伝統" },
        { en: "divorce", ja: "離婚" },
        { en: "separate (verb)", ja: "別れる" },
        { en: "engagement", ja: "婚約" },
        { en: "wedding", ja: "結婚式" },
        { en: "anniversary (family)", ja: "記念日" },
        { en: "in-law", ja: "義理の親族" },
        { en: "godparent", ja: "名付け親" },
        { en: "acquaintance", ja: "知り合い" },
        { en: "colleague", ja: "同僚" },
        { en: "classroom friend", ja: "級友" },
        { en: "best friend", ja: "親友" },
        { en: "companion", ja: "仲間" },
        { en: "individual", ja: "個人" },
        { en: "identity", ja: "アイデンティティ" },
        { en: "independent", ja: "自立した" },
        { en: "dependent", ja: "依存している" },
        { en: "mature", ja: "成熟した" },
        { en: "immature", ja: "未熟な" },
        { en: "wise", ja: "賢い" },
        { en: "stubborn", ja: "頑固な" },
        { en: "gentle", ja: "優しい" },
        { en: "strict", ja: "厳しい" },
        { en: "affectionate", ja: "愛情深い" },
        { en: "considerate", ja: "思いやりのある" },
        { en: "selfish", ja: "わがままな" },
        { en: "generous", ja: "気前の良い" },
        { en: "humble", ja: "謙虚な" },
        { en: "proud", ja: "誇りに思う" },
        { en: "ambitious", ja: "野心的な" },
        { en: "cheerful", ja: "陽気な" },
        { en: "shy", ja: "恥ずかしがりの" },
        { en: "outgoing", ja: "社交的な" },
        { en: "sibling", ja: "兄弟姉妹" },
        { en: "kinship", ja: "親族関係" },
        { en: "lineage", ja: "血統" },
        { en: "foster parent", ja: "養親" },
        { en: "adopted child", ja: "養子" },
        { en: "adoption", ja: "養子縁組" },
        { en: "eldest son", ja: "長男" },
        { en: "eldest daughter", ja: "長女" },
        { en: "youngest child", ja: "末っ子" },
        { en: "middle child", ja: "中間子" },
        { en: "blended family", ja: "混合家族" },
        { en: "nuclear family", ja: "核家族" },
        { en: "extended family", ja: "拡大家族" },
        { en: "family reunion", ja: "家族の集まり" },
        { en: "family tree", ja: "家系図" },
        { en: "genealogy", ja: "系図学" },
        { en: "birth", ja: "出生" },
        { en: "deliver (a baby)", ja: "出産する" },
        { en: "nurture", ja: "育てる（養育する）" },
        { en: "custody", ja: "親権" },
        { en: "alimony", ja: "扶養料" },
        { en: "widow", ja: "未亡人" },
        { en: "widower", ja: "やもめ（男性）" },
        { en: "orphan", ja: "孤児" },
        { en: "legal guardian", ja: "法定保護者" },
        { en: "next of kin", ja: "最も近い親族" },
        { en: "family bond", ja: "家族の絆" },
        { en: "family value", ja: "家族の価値観" },
        { en: "family gathering", ja: "家族の集い" },
        { en: "condolence", ja: "お悔やみ" },
        { en: "matriarch", ja: "女家長" },
        { en: "patriarch", ja: "家長" },
        { en: "half-sibling", ja: "異母（異父）兄弟姉妹" },
        { en: "kin", ja: "親族" },
        { en: "fiancé", ja: "婚約者（男性）" },
        { en: "fiancée", ja: "婚約者（女性）" },
        { en: "babysitter", ja: "ベビーシッター" },
        { en: "matchmaking", ja: "お見合い・縁結び" },
        { en: "childhood memory", ja: "子供の頃の思い出" },
        { en: "family tradition", ja: "家族の伝統" },
        { en: "family argument", ja: "家族げんか" },
        { en: "close relative", ja: "近親者" },
        { en: "distant relative", ja: "遠い親戚" },
        { en: "biological parent", ja: "実の親" },
        { en: "adoptive parent", ja: "養親" },
        { en: "foster child", ja: "里子" },
        { en: "single mother", ja: "シングルマザー" },
        { en: "single father", ja: "シングルファーザー" },
        { en: "family outing", ja: "家族でのお出かけ" },
        { en: "family resemblance", ja: "家族の面影" },
        { en: "blood relative", ja: "血縁者" },
        { en: "estranged", ja: "疎遠になった" },
        { en: "reunion (family)", ja: "家族の再会" },
        { en: "guardian angel", ja: "守護天使" },
        { en: "family bonding", ja: "家族の絆作り" },
        { en: "homemaker", ja: "主婦・主夫" },
        { en: "breadwinner", ja: "稼ぎ手" },
        { en: "dependent (family)", ja: "扶養家族" },
        { en: "next-door neighbor", ja: "隣人" },
        { en: "childhood friend", ja: "幼なじみ" },
        { en: "close-knit family", ja: "結束の固い家族" },
        { en: "family resemblance test", ja: "親子鑑定" },
        { en: "guardianship", ja: "後見" },
        { en: "family meeting", ja: "家族会議" },
        { en: "family budget", ja: "家計" },
        { en: "household chore", ja: "家事" },
        { en: "parental leave", ja: "育児休暇" },
        { en: "in-laws", ja: "義理の家族" },
        { en: "stepchild", ja: "継子" },
        { en: "family ties", ja: "家族の絆" },
        { en: "common-law marriage", ja: "事実婚" },
        { en: "family doctor", ja: "かかりつけ医" },
        { en: "family heirloom", ja: "家宝" },
        { en: "family crest", ja: "家紋" },
        { en: "matriarchal", ja: "母系の" },
        { en: "patriarchal", ja: "父系の" },
        { en: "blended household", ja: "再婚家庭" },
        { en: "family portrait", ja: "家族写真" },
        { en: "family vacation", ja: "家族旅行" },
        { en: "household income", ja: "世帯収入" },
        { en: "co-parenting", ja: "共同養育" },
        { en: "primary caregiver", ja: "主な養育者" },
        { en: "family counseling", ja: "家族カウンセリング" },
        { en: "extended family member", ja: "親戚の一員" },
        { en: "family history", ja: "家族の歴史" },
        { en: "family name", ja: "姓・苗字" },
        { en: "maiden name", ja: "旧姓" },
        { en: "married couple", ja: "夫婦" },
        { en: "newlyweds", ja: "新婚夫婦" },
        { en: "family dinner", ja: "家族の夕食" },
        { en: "family photo album", ja: "家族のアルバム" }
      ]
    },
    {
      id: "daily",
      name: "Daily Routine",
      emoji: "⏰",
      level: 5,
      words: [
        { en: "wake up", ja: "起きる" },
        { en: "get up", ja: "起き上がる" },
        { en: "brush (teeth)", ja: "磨く" },
        { en: "eat", ja: "食べる" },
        { en: "drink", ja: "飲む" },
        { en: "study", ja: "勉強する" },
        { en: "play", ja: "遊ぶ" },
        { en: "sleep", ja: "眠る" },
        { en: "go home", ja: "帰宅する" },
        { en: "clean", ja: "掃除する" },
        { en: "watch", ja: "見る" },
        { en: "listen", ja: "聞く" },
        { en: "take a bath", ja: "お風呂に入る" },
        { en: "get dressed", ja: "着替える" },
        { en: "make breakfast", ja: "朝食を作る" },
        { en: "do the laundry", ja: "洗濯する" },
        { en: "take out the trash", ja: "ゴミを出す" },
        { en: "walk the dog", ja: "犬を散歩させる" },
        { en: "commute", ja: "通勤・通学する" },
        { en: "relax", ja: "くつろぐ" },
        { en: "exercise", ja: "運動する" },
        { en: "check email", ja: "メールを確認する" },
        { en: "set an alarm", ja: "目覚ましをかける" },
        { en: "lock the door", ja: "ドアに鍵をかける" },
        { en: "turn off the light", ja: "電気を消す" },
        { en: "habit", ja: "習慣" },
        { en: "routine", ja: "日課" },
        { en: "schedule (verb)", ja: "予定を立てる" },
        { en: "errand", ja: "用事" },
        { en: "chore", ja: "家事" },
        { en: "wash the dishes", ja: "皿を洗う" },
        { en: "vacuum", ja: "掃除機をかける" },
        { en: "iron clothes", ja: "アイロンをかける" },
        { en: "make the bed", ja: "ベッドを整える" },
        { en: "water the plants", ja: "植物に水をやる" },
        { en: "feed the pet", ja: "ペットに餌をやる" },
        { en: "go shopping", ja: "買い物に行く" },
        { en: "cook dinner", ja: "夕食を作る" },
        { en: "pack a lunch", ja: "弁当を詰める" },
        { en: "get ready", ja: "準備する" },
        { en: "comb hair", ja: "髪をとかす" },
        { en: "shave", ja: "ひげを剃る" },
        { en: "put on makeup", ja: "化粧をする" },
        { en: "check the time", ja: "時間を確認する" },
        { en: "hurry up", ja: "急ぐ" },
        { en: "be late", ja: "遅れる" },
        { en: "arrive on time", ja: "時間通りに着く" },
        { en: "leave home", ja: "家を出る" },
        { en: "come back", ja: "戻る" },
        { en: "rest", ja: "休む" },
        { en: "nap", ja: "昼寝する" },
        { en: "stay up late", ja: "夜更かしする" },
        { en: "go to bed", ja: "寝る" },
        { en: "fall asleep", ja: "眠りに落ちる" },
        { en: "stretch", ja: "ストレッチする" },
        { en: "yawn", ja: "あくびをする" },
        { en: "brush hair", ja: "髪をブラッシングする" },
        { en: "tidy up", ja: "片付ける" },
        { en: "organize", ja: "整理する" },
        { en: "throw away", ja: "捨てる" },
        { en: "borrow", ja: "借りる" },
        { en: "lend", ja: "貸す" },
        { en: "return (something)", ja: "返す" },
        { en: "repair", ja: "修理する" },
        { en: "fix", ja: "直す" },
        { en: "charge (a phone)", ja: "充電する" },
        { en: "plug in", ja: "プラグを差し込む" },
        { en: "unplug", ja: "プラグを抜く" },
        { en: "turn on", ja: "つける" },
        { en: "turn off", ja: "消す" },
        { en: "answer the phone", ja: "電話に出る" },
        { en: "text (message)", ja: "メッセージを送る" },
        { en: "call (someone)", ja: "電話する" },
        { en: "visit", ja: "訪ねる" },
        { en: "meet up", ja: "会う" },
        { en: "hang out", ja: "遊びに出かける" },
        { en: "stay home", ja: "家にいる" },
        { en: "spend time", ja: "時間を過ごす" },
        { en: "waste time", ja: "時間を無駄にする" },
        { en: "manage time", ja: "時間を管理する" },
        { en: "be busy", ja: "忙しい" },
        { en: "be free", ja: "暇である" },
        { en: "take a break", ja: "休憩する" },
        { en: "concentrate", ja: "集中する" },
        { en: "get distracted", ja: "気が散る" },
        { en: "finish", ja: "終える" },
        { en: "start", ja: "始める" },
        { en: "continue", ja: "続ける" },
        { en: "stop", ja: "止める" },
        { en: "prepare", ja: "準備する" },
        { en: "plan", ja: "計画する" },
        { en: "remember", ja: "覚えている" },
        { en: "forget", ja: "忘れる" },
        { en: "remind", ja: "思い出させる" },
        { en: "take a shower", ja: "シャワーを浴びる" },
        { en: "floss", ja: "フロスをする" },
        { en: "gargle", ja: "うがいする" },
        { en: "put on shoes", ja: "靴を履く" },
        { en: "take off shoes", ja: "靴を脱ぐ" },
        { en: "do homework", ja: "宿題をする" },
        { en: "take notes", ja: "メモを取る" },
        { en: "pay bills", ja: "請求書を払う" },
        { en: "buy groceries", ja: "食料品を買う" },
        { en: "sort laundry", ja: "洗濯物を分ける" },
        { en: "fold clothes", ja: "服を折る" },
        { en: "hang clothes", ja: "服を干す" },
        { en: "sweep the floor", ja: "床を掃く" },
        { en: "mop the floor", ja: "床を拭く" },
        { en: "dust the furniture", ja: "家具のほこりを取る" },
        { en: "set the table", ja: "テーブルを準備する" },
        { en: "clear the table", ja: "テーブルを片付ける" },
        { en: "boil water", ja: "お湯を沸かす" },
        { en: "make coffee", ja: "コーヒーを作る" },
        { en: "read the newspaper", ja: "新聞を読む" },
        { en: "check social media", ja: "SNSを確認する" },
        { en: "update a calendar", ja: "カレンダーを更新する" },
        { en: "write a diary", ja: "日記を書く" },
        { en: "lock the bike", ja: "自転車に鍵をかける" },
        { en: "catch the bus", ja: "バスに乗る" },
        { en: "miss the bus", ja: "バスに乗り遅れる" },
        { en: "wait in line", ja: "列に並ぶ" },
        { en: "run errands", ja: "用事を済ませる" },
        { en: "check the weather", ja: "天気を確認する" },
        { en: "mow the lawn", ja: "芝を刈る" },
        { en: "take a walk", ja: "散歩する" },
        { en: "go for a run", ja: "ランニングに行く" },
        { en: "clean the bathroom", ja: "浴室を掃除する" },
        { en: "take the elevator", ja: "エレベーターに乗る" },
        { en: "take the stairs", ja: "階段を使う" },
        { en: "pack a suitcase", ja: "スーツケースを詰める" },
        { en: "hit the snooze button", ja: "スヌーズボタンを押す" },
        { en: "wash your face", ja: "顔を洗う" },
        { en: "pack your bag", ja: "かばんに荷物を詰める" },
        { en: "check the mailbox", ja: "郵便受けを確認する" },
        { en: "walk to the station", ja: "駅まで歩く" },
        { en: "take a nap", ja: "昼寝をする" },
        { en: "unlock the door", ja: "ドアの鍵を開ける" },
        { en: "tidy the room", ja: "部屋を片付ける" },
        { en: "organize the closet", ja: "クローゼットを整理する" },
        { en: "answer the door", ja: "玄関に出る" },
        { en: "polish shoes", ja: "靴を磨く" },
        { en: "sort the mail", ja: "郵便物を仕分ける" },
        { en: "check the fridge", ja: "冷蔵庫を確認する" },
        { en: "charge the laptop", ja: "ノートパソコンを充電する" },
        { en: "recycle bottles", ja: "瓶をリサイクルする" },
        { en: "write a shopping list", ja: "買い物リストを書く" },
        { en: "listen to a podcast", ja: "ポッドキャストを聞く" },
        { en: "take a quick shower", ja: "さっとシャワーを浴びる" },
        { en: "get changed", ja: "着替える" },
        { en: "put away clothes", ja: "服をしまう" },
        { en: "water the garden", ja: "庭に水をやる" },
        { en: "feed the fish", ja: "魚に餌をやる" },
        { en: "do some stretching", ja: "ストレッチをする" },
        { en: "go for a jog", ja: "ジョギングに行く" },
        { en: "make a phone call", ja: "電話をかける" },
        { en: "answer emails", ja: "メールに返信する" },
        { en: "set the alarm clock", ja: "目覚まし時計をセットする" },
        { en: "tidy your desk", ja: "机を片付ける" },
        { en: "stock the fridge", ja: "冷蔵庫に食材を補充する" },
        { en: "take medicine", ja: "薬を飲む" },
        { en: "brush a pet", ja: "ペットをブラッシングする" },
        { en: "walk up the stairs", ja: "階段を上る" },
        { en: "ride a bicycle", ja: "自転車に乗る" },
        { en: "park the car", ja: "車を駐車する" },
        { en: "fill the tank", ja: "給油する" },
        { en: "wash the car", ja: "洗車する" },
        { en: "sign a form", ja: "書類にサインする" },
        { en: "print a document", ja: "書類を印刷する" },
        { en: "scan a document", ja: "書類をスキャンする" },
        { en: "back up data", ja: "データをバックアップする" },
        { en: "update an app", ja: "アプリを更新する" },
        { en: "browse the internet", ja: "インターネットを閲覧する" },
        { en: "lock the bicycle", ja: "自転車に鍵をかける" },
        { en: "carry an umbrella", ja: "傘を持ち歩く" },
        { en: "check the schedule", ja: "予定を確認する" },
        { en: "wipe the table", ja: "テーブルを拭く" },
        { en: "empty the trash", ja: "ゴミ箱を空にする" },
        { en: "refill the water bottle", ja: "水筒を満たす" },
        { en: "turn down the volume", ja: "音量を下げる" },
        { en: "turn up the heater", ja: "暖房を強くする" },
        { en: "adjust the air conditioner", ja: "エアコンを調節する" },
        { en: "set a reminder", ja: "リマインダーを設定する" },
        { en: "skim through a book", ja: "本にざっと目を通す" },
        { en: "label a box", ja: "箱にラベルを貼る" },
        { en: "hang up the phone", ja: "電話を切る" },
        { en: "look up a word", ja: "単語を調べる" }
      ]
    },
    {
      id: "food",
      name: "Food & Drink",
      emoji: "🍙",
      level: 5,
      words: [
        { en: "rice", ja: "ご飯" },
        { en: "bread", ja: "パン" },
        { en: "milk", ja: "牛乳" },
        { en: "water", ja: "水" },
        { en: "apple", ja: "りんご" },
        { en: "orange", ja: "オレンジ" },
        { en: "egg", ja: "卵" },
        { en: "fish", ja: "魚" },
        { en: "meat", ja: "肉" },
        { en: "vegetable", ja: "野菜" },
        { en: "delicious", ja: "おいしい" },
        { en: "hungry", ja: "お腹が空いた" },
        { en: "thirsty", ja: "喉が渇いた" },
        { en: "sweet", ja: "甘い" },
        { en: "salty", ja: "しょっぱい" },
        { en: "spicy", ja: "辛い" },
        { en: "sour", ja: "酸っぱい" },
        { en: "bitter", ja: "苦い" },
        { en: "recipe", ja: "レシピ" },
        { en: "ingredient", ja: "材料" },
        { en: "flavor", ja: "味" },
        { en: "menu", ja: "メニュー" },
        { en: "order (food)", ja: "注文する" },
        { en: "leftovers", ja: "残り物" },
        { en: "snack", ja: "おやつ" },
        { en: "dessert", ja: "デザート" },
        { en: "boil", ja: "ゆでる" },
        { en: "fry", ja: "揚げる・焼く" },
        { en: "bake", ja: "焼く（オーブン）" },
        { en: "chop", ja: "刻む" },
        { en: "nutritious", ja: "栄養のある" },
        { en: "diet", ja: "食事・ダイエット" },
        { en: "appetite", ja: "食欲" },
        { en: "leftover", ja: "残った" },
        { en: "vegetarian", ja: "ベジタリアン" },
        { en: "banana", ja: "バナナ" },
        { en: "strawberry", ja: "いちご" },
        { en: "grape", ja: "ぶどう" },
        { en: "watermelon", ja: "スイカ" },
        { en: "peach", ja: "桃" },
        { en: "carrot", ja: "にんじん" },
        { en: "potato", ja: "じゃがいも" },
        { en: "onion", ja: "玉ねぎ" },
        { en: "tomato", ja: "トマト" },
        { en: "cucumber", ja: "きゅうり" },
        { en: "cabbage", ja: "キャベツ" },
        { en: "corn", ja: "とうもろこし" },
        { en: "chicken (meat)", ja: "鶏肉" },
        { en: "beef", ja: "牛肉" },
        { en: "pork", ja: "豚肉" },
        { en: "shrimp", ja: "えび" },
        { en: "noodles", ja: "麺" },
        { en: "soup", ja: "スープ" },
        { en: "salad", ja: "サラダ" },
        { en: "sandwich", ja: "サンドイッチ" },
        { en: "curry", ja: "カレー" },
        { en: "sushi", ja: "寿司" },
        { en: "cake", ja: "ケーキ" },
        { en: "cookie", ja: "クッキー" },
        { en: "ice cream", ja: "アイスクリーム" },
        { en: "chocolate", ja: "チョコレート" },
        { en: "candy", ja: "キャンディー" },
        { en: "juice", ja: "ジュース" },
        { en: "tea", ja: "お茶" },
        { en: "coffee", ja: "コーヒー" },
        { en: "soda", ja: "炭酸飲料" },
        { en: "sugar", ja: "砂糖" },
        { en: "salt", ja: "塩" },
        { en: "pepper", ja: "こしょう" },
        { en: "oil", ja: "油" },
        { en: "butter", ja: "バター" },
        { en: "cheese", ja: "チーズ" },
        { en: "yogurt", ja: "ヨーグルト" },
        { en: "sauce", ja: "ソース" },
        { en: "soy sauce", ja: "醤油" },
        { en: "chopsticks", ja: "箸" },
        { en: "fork", ja: "フォーク" },
        { en: "spoon", ja: "スプーン" },
        { en: "knife", ja: "ナイフ" },
        { en: "plate", ja: "皿" },
        { en: "bowl", ja: "ボウル" },
        { en: "cup", ja: "コップ" },
        { en: "napkin", ja: "ナプキン" },
        { en: "portion", ja: "一人前" },
        { en: "serving", ja: "一人前" },
        { en: "calorie", ja: "カロリー" },
        { en: "fat (nutrient)", ja: "脂肪" },
        { en: "protein", ja: "たんぱく質" },
        { en: "carbohydrate", ja: "炭水化物" },
        { en: "vitamin", ja: "ビタミン" },
        { en: "fresh", ja: "新鮮な" },
        { en: "rotten", ja: "腐った" },
        { en: "raw", ja: "生の" },
        { en: "frozen", ja: "冷凍の" },
        { en: "canned", ja: "缶詰の" },
        { en: "homemade", ja: "手作りの" },
        { en: "organic", ja: "有機の" },
        { en: "allergy (food)", ja: "アレルギー" },
        { en: "expiration date", ja: "賞味期限" },
        { en: "lettuce", ja: "レタス" },
        { en: "spinach", ja: "ほうれん草" },
        { en: "eggplant", ja: "なす" },
        { en: "mushroom", ja: "きのこ" },
        { en: "pumpkin", ja: "かぼちゃ" },
        { en: "garlic", ja: "にんにく" },
        { en: "ginger", ja: "しょうが" },
        { en: "lemon", ja: "レモン" },
        { en: "pineapple", ja: "パイナップル" },
        { en: "mango", ja: "マンゴー" },
        { en: "kiwi", ja: "キウイ" },
        { en: "cherry", ja: "さくらんぼ" },
        { en: "pear", ja: "梨" },
        { en: "melon", ja: "メロン" },
        { en: "squid", ja: "イカ" },
        { en: "octopus", ja: "タコ" },
        { en: "crab", ja: "カニ" },
        { en: "clam", ja: "あさり" },
        { en: "tofu", ja: "豆腐" },
        { en: "miso", ja: "味噌" },
        { en: "tempura", ja: "天ぷら" },
        { en: "ramen", ja: "ラーメン" },
        { en: "udon", ja: "うどん" },
        { en: "soba", ja: "そば" },
        { en: "dumpling", ja: "餃子" },
        { en: "pancake", ja: "パンケーキ" },
        { en: "waffle", ja: "ワッフル" },
        { en: "pudding", ja: "プリン" },
        { en: "jam", ja: "ジャム" },
        { en: "honey", ja: "はちみつ" },
        { en: "takeout", ja: "持ち帰り（テイクアウト）" },
        { en: "garnish", ja: "付け合わせ" },
        { en: "appetizer", ja: "前菜" },
        { en: "main course", ja: "メイン料理" },
        { en: "side dish", ja: "副菜" },
        { en: "seasoning", ja: "調味料" },
        { en: "broth", ja: "だし汁" },
        { en: "marinate", ja: "漬け込む" },
        { en: "grill", ja: "網焼きにする" },
        { en: "steam", ja: "蒸す" },
        { en: "stir-fry", ja: "炒める" },
        { en: "crispy", ja: "カリカリの" },
        { en: "creamy", ja: "クリーミーな" },
        { en: "bland", ja: "味が薄い" },
        { en: "allergy", ja: "アレルギー" },
        { en: "skewer", ja: "串" },
        { en: "stew", ja: "シチュー" },
        { en: "pickle", ja: "漬物" },
        { en: "leaven", ja: "発酵させる" },
        { en: "knead (dough)", ja: "生地をこねる" },
        { en: "simmer", ja: "とろ火で煮る" },
        { en: "garnish (verb)", ja: "飾り付ける" },
        { en: "appetizing", ja: "食欲をそそる" },
        { en: "tasteless", ja: "味がない" },
        { en: "rich (flavor)", ja: "コクのある" },
        { en: "light (meal)", ja: "あっさりした" },
        { en: "heavy (meal)", ja: "こってりした" },
        { en: "side order", ja: "サイドメニュー" },
        { en: "set meal", ja: "定食" },
        { en: "buffet", ja: "ビュッフェ" },
        { en: "course meal", ja: "コース料理" },
        { en: "barbecue", ja: "バーベキュー" },
        { en: "hot pot", ja: "鍋料理" },
        { en: "stir-fried noodles", ja: "焼きそば" },
        { en: "grilled fish", ja: "焼き魚" },
        { en: "fried rice", ja: "チャーハン" },
        { en: "rice ball", ja: "おにぎり" },
        { en: "bento box", ja: "弁当箱" },
        { en: "food stall", ja: "屋台" },
        { en: "food court", ja: "フードコート" },
        { en: "table manners", ja: "テーブルマナー" },
        { en: "doggy bag", ja: "持ち帰り用の袋" },
        { en: "food poisoning", ja: "食中毒" },
        { en: "kitchen utensil", ja: "調理器具" },
        { en: "frying pan", ja: "フライパン" },
        { en: "cutting board", ja: "まな板" },
        { en: "rice cooker", ja: "炊飯器" },
        { en: "blender", ja: "ミキサー" },
        { en: "microwave (food)", ja: "電子レンジで温める" },
        { en: "preheat the oven", ja: "オーブンを予熱する" },
        { en: "set the timer (cooking)", ja: "タイマーをセットする" },
        { en: "taste test", ja: "味見" },
        { en: "secret recipe", ja: "秘伝のレシピ" },
        { en: "family recipe", ja: "家族のレシピ" },
        { en: "fast food", ja: "ファストフード" },
        { en: "home cooking", ja: "家庭料理" },
        { en: "comfort food", ja: "ほっとする食べ物" }
      ]
    },
    {
      id: "town",
      name: "Town & Places",
      emoji: "🏙️",
      level: 4,
      words: [
        { en: "station", ja: "駅" },
        { en: "hospital", ja: "病院" },
        { en: "park", ja: "公園" },
        { en: "supermarket", ja: "スーパー" },
        { en: "restaurant", ja: "レストラン" },
        { en: "bookstore", ja: "本屋" },
        { en: "post office", ja: "郵便局" },
        { en: "bank", ja: "銀行" },
        { en: "museum", ja: "博物館" },
        { en: "convenience store", ja: "コンビニ" },
        { en: "city hall", ja: "市役所" },
        { en: "police station", ja: "警察署" },
        { en: "fire station", ja: "消防署" },
        { en: "airport", ja: "空港" },
        { en: "harbor", ja: "港" },
        { en: "bridge", ja: "橋" },
        { en: "intersection", ja: "交差点" },
        { en: "sidewalk", ja: "歩道" },
        { en: "crosswalk", ja: "横断歩道" },
        { en: "neighborhood", ja: "近所" },
        { en: "suburb", ja: "郊外" },
        { en: "downtown", ja: "繁華街" },
        { en: "factory", ja: "工場" },
        { en: "construction site", ja: "建設現場" },
        { en: "apartment building", ja: "マンション" },
        { en: "shopping mall", ja: "ショッピングモール" },
        { en: "parking lot", ja: "駐車場" },
        { en: "gas station", ja: "ガソリンスタンド" },
        { en: "temple", ja: "寺" },
        { en: "shrine", ja: "神社" },
        { en: "skyscraper", ja: "高層ビル" },
        { en: "population", ja: "人口" },
        { en: "facility", ja: "施設" },
        { en: "landmark", ja: "目印・名所" },
        { en: "town hall", ja: "町役場" },
        { en: "courthouse", ja: "裁判所" },
        { en: "embassy", ja: "大使館" },
        { en: "church", ja: "教会" },
        { en: "stadium", ja: "競技場" },
        { en: "gymnasium", ja: "体育館" },
        { en: "zoo", ja: "動物園" },
        { en: "aquarium", ja: "水族館" },
        { en: "amusement park", ja: "遊園地" },
        { en: "theater", ja: "劇場" },
        { en: "movie theater", ja: "映画館" },
        { en: "art gallery", ja: "美術館" },
        { en: "community center", ja: "公民館" },
        { en: "town square", ja: "広場" },
        { en: "fountain", ja: "噴水" },
        { en: "statue", ja: "像" },
        { en: "monument", ja: "記念碑" },
        { en: "cemetery", ja: "墓地" },
        { en: "farm", ja: "農場" },
        { en: "field", ja: "畑・野原" },
        { en: "forest", ja: "森" },
        { en: "mountain", ja: "山" },
        { en: "river", ja: "川" },
        { en: "lake", ja: "湖" },
        { en: "beach", ja: "ビーチ" },
        { en: "coast", ja: "海岸" },
        { en: "island", ja: "島" },
        { en: "valley", ja: "谷" },
        { en: "hill", ja: "丘" },
        { en: "road", ja: "道路" },
        { en: "street", ja: "通り" },
        { en: "avenue", ja: "大通り" },
        { en: "alley", ja: "路地" },
        { en: "block (city)", ja: "街区" },
        { en: "corner", ja: "角" },
        { en: "address", ja: "住所" },
        { en: "map", ja: "地図" },
        { en: "direction", ja: "方向" },
        { en: "distance", ja: "距離" },
        { en: "nearby", ja: "近くの" },
        { en: "far", ja: "遠い" },
        { en: "located", ja: "位置している" },
        { en: "urban", ja: "都市の" },
        { en: "rural", ja: "田舎の" },
        { en: "crowded", ja: "混雑した" },
        { en: "quiet (place)", ja: "静かな" },
        { en: "noisy", ja: "うるさい" },
        { en: "safe", ja: "安全な" },
        { en: "dangerous", ja: "危険な" },
        { en: "clean (place)", ja: "清潔な" },
        { en: "dirty", ja: "汚い" },
        { en: "modern", ja: "現代的な" },
        { en: "historic", ja: "歴史的な" },
        { en: "famous", ja: "有名な" },
        { en: "local", ja: "地元の" },
        { en: "resident", ja: "住民" },
        { en: "citizen", ja: "市民" },
        { en: "mayor", ja: "市長" },
        { en: "construction", ja: "建設" },
        { en: "renovation", ja: "改修" },
        { en: "development", ja: "開発" },
        { en: "infrastructure", ja: "インフラ" },
        { en: "sewer", ja: "下水道" },
        { en: "streetlight", ja: "街灯" },
        { en: "billboard", ja: "看板" },
        { en: "sign", ja: "標識" },
        { en: "traffic light", ja: "信号機" },
        { en: "bus stop", ja: "バス停" },
        { en: "pedestrian", ja: "歩行者" },
        { en: "roundabout", ja: "環状交差点" },
        { en: "lamppost", ja: "街灯柱" },
        { en: "manhole", ja: "マンホール" },
        { en: "overpass", ja: "高架橋" },
        { en: "underpass", ja: "地下道" },
        { en: "bike lane", ja: "自転車専用レーン" },
        { en: "speed bump", ja: "減速バンプ" },
        { en: "parking meter", ja: "パーキングメーター" },
        { en: "vending machine", ja: "自動販売機" },
        { en: "trash can", ja: "ゴミ箱" },
        { en: "laundromat", ja: "コインランドリー" },
        { en: "barber shop", ja: "理髪店" },
        { en: "hair salon", ja: "美容院" },
        { en: "pet shop", ja: "ペットショップ" },
        { en: "hardware store", ja: "金物店" },
        { en: "flower shop", ja: "花屋" },
        { en: "bakery", ja: "パン屋" },
        { en: "library card", ja: "図書館カード" },
        { en: "public restroom", ja: "公衆トイレ" },
        { en: "recycling bin", ja: "リサイクルボックス" },
        { en: "water fountain (public)", ja: "公共の噴水・水飲み場" },
        { en: "playground equipment", ja: "遊具" },
        { en: "footbridge", ja: "歩道橋" },
        { en: "town clerk", ja: "町役場の職員" },
        { en: "city center", ja: "都心" },
        { en: "city outskirts", ja: "郊外" },
        { en: "residential area", ja: "住宅地" },
        { en: "commercial district", ja: "商業地区" },
        { en: "industrial zone", ja: "工業地帯" },
        { en: "town meeting", ja: "町民集会" },
        { en: "public transportation", ja: "公共交通機関" },
        { en: "tram", ja: "路面電車" },
        { en: "monorail", ja: "モノレール" },
        { en: "bicycle parking", ja: "駐輪場" },
        { en: "crosswalk signal", ja: "横断歩道の信号" },
        { en: "town festival", ja: "町のお祭り" },
        { en: "community garden", ja: "コミュニティガーデン" },
        { en: "fire hydrant", ja: "消火栓" },
        { en: "street vendor", ja: "露店商" },
        { en: "city planning", ja: "都市計画" },
        { en: "public square", ja: "公共広場" },
        { en: "town center", ja: "町の中心部" },
        { en: "tourist information center", ja: "観光案内所" },
        { en: "city map", ja: "市街地図" },
        { en: "main street", ja: "メインストリート" },
        { en: "back alley", ja: "裏路地" },
        { en: "town gate", ja: "町の門" },
        { en: "city wall", ja: "城壁" },
        { en: "historic district", ja: "歴史地区" },
        { en: "scenic spot", ja: "景勝地" },
        { en: "local shop", ja: "地元の店" },
        { en: "open-air market", ja: "青空市場" },
        { en: "city skyline", ja: "都市の景観" }
      ]
    },
    {
      id: "hobbies",
      name: "Hobbies & Sports",
      emoji: "⚽",
      level: 4,
      words: [
        { en: "soccer", ja: "サッカー" },
        { en: "baseball", ja: "野球" },
        { en: "basketball", ja: "バスケットボール" },
        { en: "tennis", ja: "テニス" },
        { en: "swimming", ja: "水泳" },
        { en: "drawing", ja: "絵を描くこと" },
        { en: "reading", ja: "読書" },
        { en: "singing", ja: "歌うこと" },
        { en: "dancing", ja: "踊ること" },
        { en: "guitar", ja: "ギター" },
        { en: "piano", ja: "ピアノ" },
        { en: "photography", ja: "写真撮影" },
        { en: "cooking", ja: "料理" },
        { en: "gardening", ja: "ガーデニング" },
        { en: "fishing", ja: "釣り" },
        { en: "camping", ja: "キャンプ" },
        { en: "hiking", ja: "ハイキング" },
        { en: "cycling", ja: "サイクリング" },
        { en: "skating", ja: "スケート" },
        { en: "skiing", ja: "スキー" },
        { en: "volleyball", ja: "バレーボール" },
        { en: "badminton", ja: "バドミントン" },
        { en: "table tennis", ja: "卓球" },
        { en: "martial arts", ja: "武道" },
        { en: "team", ja: "チーム" },
        { en: "coach", ja: "コーチ" },
        { en: "competition", ja: "大会" },
        { en: "champion", ja: "チャンピオン" },
        { en: "practice (noun)", ja: "練習" },
        { en: "skill", ja: "技術" },
        { en: "talent", ja: "才能" },
        { en: "instrument", ja: "楽器" },
        { en: "collect", ja: "集める" },
        { en: "puzzle", ja: "パズル" },
        { en: "rugby", ja: "ラグビー" },
        { en: "golf", ja: "ゴルフ" },
        { en: "surfing", ja: "サーフィン" },
        { en: "snowboarding", ja: "スノーボード" },
        { en: "judo", ja: "柔道" },
        { en: "karate", ja: "空手" },
        { en: "kendo", ja: "剣道" },
        { en: "sumo wrestling", ja: "相撲" },
        { en: "boxing", ja: "ボクシング" },
        { en: "archery", ja: "アーチェリー" },
        { en: "fencing", ja: "フェンシング" },
        { en: "horse riding", ja: "乗馬" },
        { en: "sailing", ja: "セーリング" },
        { en: "rowing", ja: "ボート競技" },
        { en: "climbing", ja: "クライミング" },
        { en: "mountain climbing", ja: "登山" },
        { en: "bowling", ja: "ボウリング" },
        { en: "darts", ja: "ダーツ" },
        { en: "billiards", ja: "ビリヤード" },
        { en: "chess", ja: "チェス" },
        { en: "shogi", ja: "将棋" },
        { en: "card game", ja: "カードゲーム" },
        { en: "board game", ja: "ボードゲーム" },
        { en: "video game", ja: "テレビゲーム" },
        { en: "gamer", ja: "ゲーマー" },
        { en: "knitting", ja: "編み物" },
        { en: "sewing", ja: "縫い物" },
        { en: "painting", ja: "絵画" },
        { en: "sculpture", ja: "彫刻" },
        { en: "pottery", ja: "陶芸" },
        { en: "calligraphy", ja: "書道" },
        { en: "origami", ja: "折り紙" },
        { en: "model building", ja: "モデル作り" },
        { en: "woodworking", ja: "木工" },
        { en: "ballet", ja: "バレエ" },
        { en: "choir", ja: "合唱団" },
        { en: "band (music)", ja: "バンド" },
        { en: "orchestra", ja: "オーケストラ" },
        { en: "drum", ja: "ドラム" },
        { en: "violin", ja: "バイオリン" },
        { en: "flute", ja: "フルート" },
        { en: "trumpet", ja: "トランペット" },
        { en: "saxophone", ja: "サックス" },
        { en: "ukulele", ja: "ウクレレ" },
        { en: "songwriting", ja: "作詞作曲" },
        { en: "scrapbooking", ja: "スクラップブッキング" },
        { en: "journaling", ja: "日記をつけること" },
        { en: "blogging", ja: "ブログを書くこと" },
        { en: "cosplay", ja: "コスプレ" },
        { en: "anime", ja: "アニメ" },
        { en: "manga", ja: "マンガ" },
        { en: "novel", ja: "小説" },
        { en: "poetry", ja: "詩" },
        { en: "magic tricks", ja: "マジック" },
        { en: "juggling", ja: "ジャグリング" },
        { en: "yoga", ja: "ヨガ" },
        { en: "meditation", ja: "瞑想" },
        { en: "jogging", ja: "ジョギング" },
        { en: "running", ja: "ランニング" },
        { en: "marathon", ja: "マラソン" },
        { en: "weightlifting", ja: "ウエイトリフティング" },
        { en: "birdwatching", ja: "野鳥観察" },
        { en: "stargazing", ja: "星空観察" },
        { en: "collecting stamps", ja: "切手収集" },
        { en: "collecting coins", ja: "コイン収集" },
        { en: "model trains", ja: "鉄道模型" },
        { en: "baking", ja: "お菓子作り" },
        { en: "tea ceremony", ja: "茶道" },
        { en: "flower arrangement", ja: "華道" },
        { en: "DIY", ja: "自分で作ること" },
        { en: "embroidery", ja: "刺繍" },
        { en: "candle making", ja: "キャンドル作り" },
        { en: "soap making", ja: "石けん作り" },
        { en: "beekeeping", ja: "養蜂" },
        { en: "model airplane", ja: "模型飛行機" },
        { en: "geocaching", ja: "ジオキャッシング" },
        { en: "paddleboarding", ja: "パドルボード" },
        { en: "kayaking", ja: "カヤック" },
        { en: "canoeing", ja: "カヌー" },
        { en: "diving", ja: "ダイビング" },
        { en: "playing chess", ja: "チェスをすること" },
        { en: "skateboarding", ja: "スケートボード" },
        { en: "karaoke", ja: "カラオケ" },
        { en: "scuba diving", ja: "スキューバダイビング" },
        { en: "rock climbing", ja: "ロッククライミング" },
        { en: "ice skating", ja: "アイススケート" },
        { en: "treasure hunting", ja: "宝探し" },
        { en: "scrapbook making", ja: "スクラップブック作り" },
        { en: "puzzle solving", ja: "パズルを解くこと" },
        { en: "stand-up paddling", ja: "サップ" },
        { en: "bouldering", ja: "ボルダリング" },
        { en: "parkour", ja: "パルクール" },
        { en: "wood carving", ja: "木彫り" },
        { en: "leatherworking", ja: "革細工" },
        { en: "glassblowing", ja: "ガラス吹き" },
        { en: "metal detecting", ja: "金属探知" },
        { en: "drone flying", ja: "ドローン操縦" },
        { en: "esports", ja: "eスポーツ" },
        { en: "amateur radio", ja: "アマチュア無線" },
        { en: "stand-up comedy", ja: "スタンドアップコメディ" },
        { en: "film making", ja: "映画制作" },
        { en: "podcasting", ja: "ポッドキャスト制作" },
        { en: "vlogging", ja: "ブイログ撮影" },
        { en: "street dance", ja: "ストリートダンス" },
        { en: "salsa dancing", ja: "サルサダンス" },
        { en: "ballroom dancing", ja: "社交ダンス" },
        { en: "bird feeding", ja: "野鳥への餌やり" },
        { en: "aquarium keeping", ja: "アクアリウム" },
        { en: "terrarium making", ja: "テラリウム作り" },
        { en: "bonsai", ja: "盆栽" },
        { en: "ikebana", ja: "生け花" },
        { en: "wine tasting", ja: "ワインテイスティング" },
        { en: "coffee brewing", ja: "コーヒー抽出" },
        { en: "tea tasting", ja: "お茶の試飲" },
        { en: "home brewing", ja: "自家醸造" },
        { en: "cheese making", ja: "チーズ作り" },
        { en: "bread making", ja: "パン作り" },
        { en: "cake decorating", ja: "ケーキ装飾" },
        { en: "furniture making", ja: "家具作り" },
        { en: "robotics", ja: "ロボット工学" },
        { en: "coding (hobby)", ja: "プログラミング（趣味として）" },
        { en: "app development", ja: "アプリ開発" },
        { en: "stop-motion animation", ja: "コマ撮りアニメ" },
        { en: "graphic design", ja: "グラフィックデザイン" },
        { en: "fashion design", ja: "ファッションデザイン" },
        { en: "jewelry making", ja: "アクセサリー作り" }
      ]
    },
    {
      id: "weather-time",
      name: "Weather & Time",
      emoji: "☀️",
      level: 4,
      words: [
        { en: "sunny", ja: "晴れの" },
        { en: "rainy", ja: "雨の" },
        { en: "cloudy", ja: "曇りの" },
        { en: "snowy", ja: "雪の" },
        { en: "windy", ja: "風が強い" },
        { en: "today", ja: "今日" },
        { en: "tomorrow", ja: "明日" },
        { en: "yesterday", ja: "昨日" },
        { en: "morning", ja: "朝" },
        { en: "evening", ja: "夕方" },
        { en: "humid", ja: "湿気の多い" },
        { en: "foggy", ja: "霧の" },
        { en: "thunderstorm", ja: "雷雨" },
        { en: "temperature", ja: "気温" },
        { en: "forecast", ja: "予報" },
        { en: "season", ja: "季節" },
        { en: "spring", ja: "春" },
        { en: "summer", ja: "夏" },
        { en: "autumn", ja: "秋" },
        { en: "winter", ja: "冬" },
        { en: "century", ja: "世紀" },
        { en: "decade", ja: "10年間" },
        { en: "anniversary", ja: "記念日" },
        { en: "deadline", ja: "締め切り" },
        { en: "punctual", ja: "時間を守る" },
        { en: "in advance", ja: "前もって" },
        { en: "eventually", ja: "結局" },
        { en: "recently", ja: "最近" },
        { en: "frequently", ja: "頻繁に" },
        { en: "occasionally", ja: "時々" },
        { en: "hail", ja: "あられ・ひょう" },
        { en: "drizzle", ja: "小雨" },
        { en: "storm", ja: "嵐" },
        { en: "typhoon", ja: "台風" },
        { en: "hurricane", ja: "ハリケーン" },
        { en: "tornado", ja: "竜巻" },
        { en: "lightning", ja: "雷（光）" },
        { en: "thunder", ja: "雷（音）" },
        { en: "rainbow", ja: "虹" },
        { en: "drought", ja: "干ばつ" },
        { en: "flood", ja: "洪水" },
        { en: "heat wave", ja: "熱波" },
        { en: "cold wave", ja: "寒波" },
        { en: "frost", ja: "霜" },
        { en: "ice", ja: "氷" },
        { en: "dew", ja: "露" },
        { en: "mist", ja: "もや" },
        { en: "breeze", ja: "そよ風" },
        { en: "gale", ja: "強風" },
        { en: "degree (temperature)", ja: "度" },
        { en: "Celsius", ja: "摂氏" },
        { en: "Fahrenheit", ja: "華氏" },
        { en: "humidity", ja: "湿度" },
        { en: "barometer", ja: "気圧計" },
        { en: "thermometer", ja: "温度計" },
        { en: "weather forecaster", ja: "気象予報士" },
        { en: "clear sky", ja: "晴天" },
        { en: "overcast", ja: "どんよりした" },
        { en: "mild (weather)", ja: "温暖な" },
        { en: "chilly", ja: "肌寒い" },
        { en: "freezing", ja: "凍えるような" },
        { en: "scorching", ja: "焼け付くように暑い" },
        { en: "dawn", ja: "夜明け" },
        { en: "dusk", ja: "夕暮れ" },
        { en: "noon", ja: "正午" },
        { en: "midnight", ja: "真夜中" },
        { en: "midday", ja: "真昼" },
        { en: "afternoon", ja: "午後" },
        { en: "night", ja: "夜" },
        { en: "weekday", ja: "平日" },
        { en: "weekend", ja: "週末" },
        { en: "holiday", ja: "祝日" },
        { en: "month", ja: "月" },
        { en: "week", ja: "週" },
        { en: "hour", ja: "時間" },
        { en: "minute", ja: "分" },
        { en: "second (time)", ja: "秒" },
        { en: "moment", ja: "瞬間" },
        { en: "instant", ja: "瞬時" },
        { en: "period (time)", ja: "期間" },
        { en: "era", ja: "時代" },
        { en: "past", ja: "過去" },
        { en: "present (time)", ja: "現在" },
        { en: "future", ja: "未来" },
        { en: "ago", ja: "前" },
        { en: "later", ja: "後で" },
        { en: "soon", ja: "すぐに" },
        { en: "immediately", ja: "直ちに" },
        { en: "afterward", ja: "その後" },
        { en: "beforehand", ja: "前もって" },
        { en: "meanwhile", ja: "その間に" },
        { en: "nowadays", ja: "近頃は" },
        { en: "previously", ja: "以前に" },
        { en: "constantly", ja: "絶え間なく" },
        { en: "rarely", ja: "稀に" },
        { en: "seldom", ja: "めったに〜ない" },
        { en: "annually", ja: "毎年" },
        { en: "monthly", ja: "毎月" },
        { en: "weekly", ja: "毎週" },
        { en: "ahead of schedule", ja: "予定より早く" },
        { en: "behind schedule", ja: "予定より遅れて" },
        { en: "blizzard", ja: "猛吹雪" },
        { en: "heatstroke", ja: "熱中症" },
        { en: "sunrise", ja: "日の出" },
        { en: "sunset", ja: "日没" },
        { en: "twilight", ja: "たそがれ" },
        { en: "leap year", ja: "うるう年" },
        { en: "fiscal year", ja: "会計年度" },
        { en: "time difference", ja: "時差" },
        { en: "wristwatch", ja: "腕時計" },
        { en: "stopwatch", ja: "ストップウォッチ" },
        { en: "boiling hot", ja: "うだるように暑い" },
        { en: "overdue", ja: "期限を過ぎた" },
        { en: "downpour", ja: "土砂降り" },
        { en: "shower (rain)", ja: "にわか雨" },
        { en: "sleet", ja: "みぞれ" },
        { en: "monsoon", ja: "モンスーン" },
        { en: "heat index", ja: "暑さ指数" },
        { en: "weather warning", ja: "気象警報" },
        { en: "weather alert", ja: "気象注意報" },
        { en: "daybreak", ja: "夜明け" },
        { en: "nightfall", ja: "日暮れ" },
        { en: "off-season", ja: "オフシーズン" },
        { en: "peak season", ja: "最盛期" },
        { en: "ahead of time", ja: "前もって" },
        { en: "on schedule", ja: "予定通りに" },
        { en: "rain or shine", ja: "雨天決行" },
        { en: "weather permitting", ja: "天候が良ければ" },
        { en: "time slot", ja: "時間枠" },
        { en: "timekeeper", ja: "計時係" },
        { en: "leap second", ja: "うるう秒" },
        { en: "in the long run", ja: "長い目で見れば" },
        { en: "for the time being", ja: "当分の間" },
        { en: "year-round", ja: "一年中" },
        { en: "biannual", ja: "年に2回の" },
        { en: "quarterly", ja: "四半期ごとの" },
        { en: "overnight", ja: "一晩中" },
        { en: "around the clock", ja: "24時間体制で" },
        { en: "time capsule", ja: "タイムカプセル" },
        { en: "season change", ja: "季節の変わり目" },
        { en: "rainy season", ja: "梅雨" },
        { en: "dry season", ja: "乾季" },
        { en: "wet season", ja: "雨季" },
        { en: "cherry blossom season", ja: "桜の季節" },
        { en: "harvest season", ja: "収穫の季節" },
        { en: "weather pattern", ja: "気象パターン" },
        { en: "weather conditions", ja: "気象状況" },
        { en: "extreme weather", ja: "異常気象" },
        { en: "climate change", ja: "気候変動" },
        { en: "seasonal", ja: "季節的な" },
        { en: "punctually", ja: "時間通りに" },
        { en: "on time", ja: "時間通りに（オンタイム）" }
      ]
    },
    {
      id: "travel",
      name: "Travel & Transportation",
      emoji: "✈️",
      level: 3,
      words: [
        { en: "passport", ja: "パスポート" },
        { en: "luggage", ja: "荷物" },
        { en: "ticket", ja: "切符・チケット" },
        { en: "reservation", ja: "予約" },
        { en: "destination", ja: "目的地" },
        { en: "departure", ja: "出発" },
        { en: "arrival", ja: "到着" },
        { en: "delay", ja: "遅延" },
        { en: "platform", ja: "プラットホーム" },
        { en: "boarding pass", ja: "搭乗券" },
        { en: "customs", ja: "税関" },
        { en: "tour guide", ja: "ツアーガイド" },
        { en: "sightseeing", ja: "観光" },
        { en: "souvenir", ja: "お土産" },
        { en: "currency", ja: "通貨" },
        { en: "exchange rate", ja: "為替レート" },
        { en: "itinerary", ja: "旅程" },
        { en: "accommodation", ja: "宿泊施設" },
        { en: "highway", ja: "高速道路" },
        { en: "traffic jam", ja: "交通渋滞" },
        { en: "subway", ja: "地下鉄" },
        { en: "ferry", ja: "フェリー" },
        { en: "round trip", ja: "往復" },
        { en: "one-way", ja: "片道" },
        { en: "transfer (trains)", ja: "乗り換え" },
        { en: "abroad", ja: "海外で" },
        { en: "foreign", ja: "外国の" },
        { en: "culture", ja: "文化" },
        { en: "tradition", ja: "伝統" },
        { en: "explore", ja: "探検する" },
        { en: "airline", ja: "航空会社" },
        { en: "flight", ja: "フライト" },
        { en: "airplane", ja: "飛行機" },
        { en: "pilot", ja: "パイロット" },
        { en: "flight attendant", ja: "フライトアテンダント" },
        { en: "runway", ja: "滑走路" },
        { en: "terminal", ja: "ターミナル" },
        { en: "check-in", ja: "チェックイン" },
        { en: "baggage claim", ja: "荷物受取所" },
        { en: "visa", ja: "ビザ" },
        { en: "immigration", ja: "入国管理" },
        { en: "tour", ja: "旅行・ツアー" },
        { en: "tourist", ja: "観光客" },
        { en: "backpacker", ja: "バックパッカー" },
        { en: "hotel", ja: "ホテル" },
        { en: "hostel", ja: "ホステル" },
        { en: "inn", ja: "旅館" },
        { en: "campsite", ja: "キャンプ場" },
        { en: "resort", ja: "リゾート" },
        { en: "cruise", ja: "クルーズ" },
        { en: "cruise ship", ja: "クルーズ船" },
        { en: "cabin (ship/train)", ja: "客室" },
        { en: "compartment", ja: "コンパートメント" },
        { en: "taxi", ja: "タクシー" },
        { en: "rental car", ja: "レンタカー" },
        { en: "driver's license", ja: "運転免許証" },
        { en: "compass", ja: "コンパス" },
        { en: "guidebook", ja: "ガイドブック" },
        { en: "local cuisine", ja: "郷土料理" },
        { en: "local custom", ja: "地元の習慣" },
        { en: "language barrier", ja: "言語の壁" },
        { en: "translator", ja: "翻訳者" },
        { en: "interpreter", ja: "通訳者" },
        { en: "jet lag", ja: "時差ボケ" },
        { en: "time zone", ja: "タイムゾーン" },
        { en: "domestic (travel)", ja: "国内の" },
        { en: "international", ja: "国際的な" },
        { en: "overseas", ja: "海外の" },
        { en: "continent", ja: "大陸" },
        { en: "border", ja: "国境" },
        { en: "immigration officer", ja: "入国審査官" },
        { en: "tour package", ja: "パッケージツアー" },
        { en: "travel agency", ja: "旅行代理店" },
        { en: "travel insurance", ja: "旅行保険" },
        { en: "layover", ja: "経由" },
        { en: "connecting flight", ja: "乗り継ぎ便" },
        { en: "nonstop flight", ja: "直行便" },
        { en: "economy class", ja: "エコノミークラス" },
        { en: "business class", ja: "ビジネスクラス" },
        { en: "first class", ja: "ファーストクラス" },
        { en: "seat belt", ja: "シートベルト" },
        { en: "overhead compartment", ja: "上部の収納スペース" },
        { en: "duty-free", ja: "免税の" },
        { en: "exchange (money)", ja: "両替する" },
        { en: "budget travel", ja: "格安旅行" },
        { en: "backpacking trip", ja: "バックパック旅行" },
        { en: "road trip", ja: "ドライブ旅行" },
        { en: "tour bus", ja: "観光バス" },
        { en: "cable car", ja: "ケーブルカー" },
        { en: "boat", ja: "ボート" },
        { en: "cruise port", ja: "クルーズ港" },
        { en: "departure lounge", ja: "出発ラウンジ" },
        { en: "arrival gate", ja: "到着ゲート" },
        { en: "excursion", ja: "小旅行" },
        { en: "expedition", ja: "探検旅行" },
        { en: "wanderlust", ja: "旅への憧れ" },
        { en: "journey", ja: "旅" },
        { en: "carry-on bag", ja: "機内持ち込みかばん" },
        { en: "window seat", ja: "窓側の席" },
        { en: "aisle seat", ja: "通路側の席" },
        { en: "scenic route", ja: "景色の良い道" },
        { en: "local market", ja: "地元の市場" },
        { en: "street food", ja: "屋台料理" },
        { en: "travel diary", ja: "旅日記" },
        { en: "travel companion", ja: "旅の連れ" },
        { en: "travel checklist", ja: "旅行の持ち物リスト" },
        { en: "cultural exchange", ja: "文化交流" },
        { en: "world heritage site", ja: "世界遺産" },
        { en: "check in (hotel)", ja: "チェックインする" },
        { en: "check out (hotel)", ja: "チェックアウトする" },
        { en: "tour itinerary", ja: "ツアー日程" },
        { en: "sightseeing spot", ja: "観光名所" },
        { en: "travel budget", ja: "旅行予算" },
        { en: "currency exchange", ja: "両替" },
        { en: "travel guidebook", ja: "旅行ガイドブック" },
        { en: "local transportation", ja: "地元の交通機関" },
        { en: "scenic view", ja: "景勝地" },
        { en: "tourist trap", ja: "観光客向けの罠（場所）" },
        { en: "off the beaten path", ja: "人があまり行かない場所" },
        { en: "travel souvenir shop", ja: "お土産屋" },
        { en: "tour reservation", ja: "ツアー予約" },
        { en: "passport control", ja: "出入国管理" },
        { en: "travel visa application", ja: "観光ビザ申請" },
        { en: "travel itinerary planner", ja: "旅程プランナー" },
        { en: "frequent flyer", ja: "搭乗マイル会員" },
        { en: "travel voucher", ja: "旅行クーポン" },
        { en: "city tour", ja: "市内観光" },
        { en: "walking tour", ja: "ウォーキングツアー" },
        { en: "tour group", ja: "団体旅行" },
        { en: "solo travel", ja: "一人旅" },
        { en: "honeymoon trip", ja: "新婚旅行" },
        { en: "business trip", ja: "出張" },
        { en: "weekend getaway", ja: "週末旅行" },
        { en: "tourist visa", ja: "観光ビザ" },
        { en: "travel restriction", ja: "渡航制限" },
        { en: "travel advisory", ja: "渡航情報" },
        { en: "travel permit", ja: "渡航許可証" },
        { en: "travel document", ja: "渡航書類" },
        { en: "travel route", ja: "旅行ルート" },
        { en: "departure time", ja: "出発時刻" },
        { en: "arrival time", ja: "到着時刻" },
        { en: "flight delay", ja: "フライト遅延" },
        { en: "flight cancellation", ja: "フライト欠航" },
        { en: "tour fee", ja: "ツアー料金" },
        { en: "hotel reservation", ja: "ホテルの予約" },
        { en: "guided tour", ja: "ガイド付きツアー" },
        { en: "self-guided tour", ja: "自由散策ツアー" },
        { en: "travel blog", ja: "旅行ブログ" },
        { en: "travel photography", ja: "旅の写真撮影" }
      ]
    },
    {
      id: "society",
      name: "Society & Environment",
      emoji: "🌍",
      level: 3,
      words: [
        { en: "environment", ja: "環境" },
        { en: "pollution", ja: "汚染" },
        { en: "recycle", ja: "リサイクルする" },
        { en: "resource", ja: "資源" },
        { en: "energy", ja: "エネルギー" },
        { en: "climate", ja: "気候" },
        { en: "global warming", ja: "地球温暖化" },
        { en: "endangered", ja: "絶滅の危機にある" },
        { en: "wildlife", ja: "野生動物" },
        { en: "ecosystem", ja: "生態系" },
        { en: "government", ja: "政府" },
        { en: "election", ja: "選挙" },
        { en: "economy", ja: "経済" },
        { en: "industry", ja: "産業" },
        { en: "technology", ja: "技術" },
        { en: "invention", ja: "発明" },
        { en: "communication", ja: "コミュニケーション" },
        { en: "community", ja: "地域社会" },
        { en: "volunteer", ja: "ボランティア" },
        { en: "charity", ja: "慈善事業" },
        { en: "responsibility", ja: "責任" },
        { en: "opportunity", ja: "機会" },
        { en: "challenge", ja: "課題・挑戦" },
        { en: "solution", ja: "解決策" },
        { en: "issue", ja: "問題" },
        { en: "policy", ja: "政策" },
        { en: "law", ja: "法律" },
        { en: "tax", ja: "税金" },
        { en: "income", ja: "収入" },
        { en: "poverty", ja: "貧困" },
        { en: "democracy", ja: "民主主義" },
        { en: "vote", ja: "投票する" },
        { en: "candidate", ja: "候補者" },
        { en: "parliament", ja: "議会" },
        { en: "president", ja: "大統領" },
        { en: "prime minister", ja: "首相" },
        { en: "diplomacy", ja: "外交" },
        { en: "international relations", ja: "国際関係" },
        { en: "human rights", ja: "人権" },
        { en: "equality", ja: "平等" },
        { en: "discrimination", ja: "差別" },
        { en: "gender equality", ja: "男女平等" },
        { en: "minority", ja: "少数派" },
        { en: "immigrant", ja: "移民" },
        { en: "refugee", ja: "難民" },
        { en: "globalization", ja: "グローバル化" },
        { en: "unemployment", ja: "失業" },
        { en: "employment", ja: "雇用" },
        { en: "labor", ja: "労働" },
        { en: "wage", ja: "賃金" },
        { en: "welfare", ja: "福祉" },
        { en: "social security", ja: "社会保障" },
        { en: "healthcare", ja: "医療" },
        { en: "insurance", ja: "保険" },
        { en: "inflation", ja: "インフレーション" },
        { en: "recession", ja: "不況" },
        { en: "budget", ja: "予算" },
        { en: "investment", ja: "投資" },
        { en: "trade", ja: "貿易" },
        { en: "import", ja: "輸入" },
        { en: "export", ja: "輸出" },
        { en: "consumer", ja: "消費者" },
        { en: "producer", ja: "生産者" },
        { en: "manufacturing", ja: "製造業" },
        { en: "agriculture", ja: "農業" },
        { en: "sustainability", ja: "持続可能性" },
        { en: "renewable energy", ja: "再生可能エネルギー" },
        { en: "solar power", ja: "太陽光発電" },
        { en: "wind power", ja: "風力発電" },
        { en: "fossil fuel", ja: "化石燃料" },
        { en: "carbon emission", ja: "二酸化炭素排出" },
        { en: "deforestation", ja: "森林破壊" },
        { en: "conservation", ja: "保全" },
        { en: "biodiversity", ja: "生物多様性" },
        { en: "natural disaster", ja: "自然災害" },
        { en: "earthquake", ja: "地震" },
        { en: "famine", ja: "飢饉" },
        { en: "epidemic", ja: "流行病" },
        { en: "pandemic", ja: "世界的流行病" },
        { en: "vaccine", ja: "ワクチン" },
        { en: "public health", ja: "公衆衛生" },
        { en: "crime", ja: "犯罪" },
        { en: "justice", ja: "正義" },
        { en: "court", ja: "裁判" },
        { en: "judge", ja: "裁判官" },
        { en: "lawyer", ja: "弁護士" },
        { en: "constitution", ja: "憲法" },
        { en: "freedom", ja: "自由" },
        { en: "censorship", ja: "検閲" },
        { en: "media", ja: "メディア" },
        { en: "journalism", ja: "ジャーナリズム" },
        { en: "propaganda", ja: "プロパガンダ" },
        { en: "social media", ja: "ソーシャルメディア" },
        { en: "artificial intelligence", ja: "人工知能" },
        { en: "innovation", ja: "革新" },
        { en: "automation", ja: "自動化" },
        { en: "urbanization", ja: "都市化" },
        { en: "population", ja: "人口" },
        { en: "civil rights", ja: "公民権" },
        { en: "social welfare", ja: "社会福祉" },
        { en: "minimum wage", ja: "最低賃金" },
        { en: "income gap", ja: "所得格差" },
        { en: "social justice", ja: "社会正義" },
        { en: "public opinion", ja: "世論" },
        { en: "civic duty", ja: "市民の義務" },
        { en: "diversity", ja: "多様性" },
        { en: "cultural heritage", ja: "文化遺産" },
        { en: "social change", ja: "社会変化" },
        { en: "collective action", ja: "集団行動" },
        { en: "recycling", ja: "リサイクル" },
        { en: "social media influence", ja: "ソーシャルメディアの影響力" },
        { en: "freedom of speech", ja: "言論の自由" },
        { en: "voter turnout", ja: "投票率" },
        { en: "public service", ja: "公共サービス" },
        { en: "tax reform", ja: "税制改革" },
        { en: "economic growth", ja: "経済成長" },
        { en: "social inequality", ja: "社会的不平等" },
        { en: "labor union", ja: "労働組合" },
        { en: "consumer rights", ja: "消費者の権利" },
        { en: "data privacy", ja: "データプライバシー" },
        { en: "cybersecurity", ja: "サイバーセキュリティ" },
        { en: "misinformation", ja: "誤情報" },
        { en: "civic engagement", ja: "市民参加" },
        { en: "social responsibility", ja: "社会的責任" },
        { en: "corporate responsibility", ja: "企業の社会的責任" },
        { en: "public infrastructure", ja: "公共インフラ" },
        { en: "social mobility", ja: "社会的流動性" },
        { en: "aging society", ja: "高齢化社会" },
        { en: "declining birthrate", ja: "少子化" },
        { en: "work-life balance", ja: "ワークライフバランス" },
        { en: "remote work", ja: "リモートワーク" },
        { en: "gig economy", ja: "ギグエコノミー" },
        { en: "national debt", ja: "国の借金" },
        { en: "public funding", ja: "公的資金" },
        { en: "grassroots movement", ja: "草の根運動" },
        { en: "social cohesion", ja: "社会的結束" },
        { en: "public awareness", ja: "公衆の意識" },
        { en: "social stigma", ja: "社会的な偏見" },
        { en: "social norm violation", ja: "社会規範違反" },
        { en: "ethical dilemma", ja: "倫理的ジレンマ" },
        { en: "moral obligation", ja: "道義的責任" },
        { en: "public debate", ja: "公開討論" },
        { en: "social experiment", ja: "社会実験" },
        { en: "community outreach", ja: "地域社会への働きかけ" },
        { en: "nonprofit organization", ja: "非営利団体" },
        { en: "government subsidy", ja: "政府補助金" },
        { en: "social safety net", ja: "社会的セーフティネット" },
        { en: "generational gap", ja: "世代間格差" },
        { en: "cultural identity", ja: "文化的アイデンティティ" }
      ]
    }
  ];

  // ---- Sentence-pattern questions (word-order builder) ----
  // tokens: words in CORRECT order. The game will shuffle them for the student.
  // "level" roughly maps to Eiken levels: 5 (easiest) -> 4 -> 3 -> pre2 -> 2.
  var SENTENCES = [
    // --- Eiken 5 (simple present/past, basic questions) ---
    { level: 5, tokens: ["I", "am", "a", "student", "."], ja: "私は学生です。" },
    { level: 5, tokens: ["She", "is", "my", "sister", "."], ja: "彼女は私の姉です。" },
    { level: 5, tokens: ["I", "eat", "breakfast", "every", "day", "."], ja: "私は毎日朝食を食べます。" },
    { level: 5, tokens: ["He", "plays", "soccer", "on", "Sunday", "."], ja: "彼は日曜日にサッカーをします。" },
    { level: 5, tokens: ["Do", "you", "like", "music", "?"], ja: "あなたは音楽が好きですか。" },
    { level: 5, tokens: ["What", "time", "is", "it", "?"], ja: "今何時ですか。" },
    { level: 5, tokens: ["This", "is", "my", "pencil", "."], ja: "これは私の鉛筆です。" },
    { level: 5, tokens: ["I", "am", "studying", "English", "now", "."], ja: "私は今英語を勉強しています。" },

    // --- Eiken 4 (past tense, simple negatives, want to / can) ---
    { level: 4, tokens: ["I", "went", "to", "school", "yesterday", "."], ja: "私は昨日学校に行きました。" },
    { level: 4, tokens: ["She", "did", "not", "eat", "lunch", "."], ja: "彼女は昼食を食べませんでした。" },
    { level: 4, tokens: ["Where", "is", "the", "station", "?"], ja: "駅はどこですか。" },
    { level: 4, tokens: ["I", "want", "to", "be", "a", "teacher", "."], ja: "私は先生になりたいです。" },
    { level: 4, tokens: ["He", "was", "playing", "tennis", "."], ja: "彼はテニスをしていました。" },
    { level: 4, tokens: ["Can", "you", "help", "me", "?"], ja: "手伝ってくれますか。" },

    // --- Eiken 3 (conjunctions: because, when, if, after, before) ---
    { level: 3, tokens: ["I", "was", "happy", "because", "I", "passed", "the", "test", "."], ja: "テストに合格したので、私はうれしかったです。" },
    { level: 3, tokens: ["When", "I", "got", "home", ",", "it", "was", "raining", "."], ja: "私が家に着いたとき、雨が降っていました。" },
    { level: 3, tokens: ["If", "it", "rains", "tomorrow", ",", "we", "will", "stay", "home", "."], ja: "もし明日雨が降ったら、私たちは家にいます。" },
    { level: 3, tokens: ["After", "I", "finish", "my", "homework", ",", "I", "will", "watch", "TV", "."], ja: "宿題を終えた後、テレビを見ます。" },
    { level: 3, tokens: ["Before", "you", "go", "out", ",", "please", "lock", "the", "door", "."], ja: "外出する前に、ドアに鍵をかけてください。" },
    { level: 3, tokens: ["She", "studies", "hard", "so", "that", "she", "can", "pass", "the", "exam", "."], ja: "彼女は試験に合格できるように一生懸命勉強します。" },
    { level: 3, tokens: ["I", "have", "lived", "here", "since", "I", "was", "a", "child", "."], ja: "私は子どもの頃からここに住んでいます。" },
    { level: 3, tokens: ["He", "is", "too", "tired", "to", "walk", "any", "farther", "."], ja: "彼は疲れすぎてこれ以上歩けません。" },

    // --- Eiken Pre-2 / 2 (relative clauses, passive voice, comparisons, although) ---
    { level: 2, tokens: ["The", "book", "that", "I", "bought", "yesterday", "is", "very", "interesting", "."], ja: "私が昨日買った本はとても面白いです。" },
    { level: 2, tokens: ["Although", "it", "was", "raining", ",", "we", "decided", "to", "go", "out", "."], ja: "雨が降っていましたが、私たちは外出することにしました。" },
    { level: 2, tokens: ["This", "house", "was", "built", "by", "my", "grandfather", "."], ja: "この家は私の祖父によって建てられました。" },
    { level: 2, tokens: ["The", "more", "you", "practice", ",", "the", "better", "you", "become", "."], ja: "練習すればするほど、上手になります。" },
    { level: 2, tokens: ["She", "is", "the", "kindest", "person", "that", "I", "have", "ever", "met", "."], ja: "彼女は私が今まで会った中で最も優しい人です。" },
    { level: 2, tokens: ["Unless", "you", "hurry", "up", ",", "you", "will", "miss", "the", "train", "."], ja: "急がない限り、電車に乗り遅れますよ。" },
    { level: 2, tokens: ["I", "wonder", "if", "he", "will", "come", "to", "the", "party", "."], ja: "彼がパーティーに来るかどうか気になります。" },
    { level: 2, tokens: ["By", "the", "time", "we", "arrived", ",", "the", "concert", "had", "already", "started", "."], ja: "私たちが到着するまでに、コンサートはすでに始まっていました。" },
    { level: 2, tokens: ["It", "is", "important", "for", "students", "to", "manage", "their", "time", "well", "."], ja: "生徒にとって時間をうまく管理することが大切です。" },
    { level: 2, tokens: ["Not", "only", "did", "she", "win", "the", "race", ",", "but", "she", "also", "broke", "the", "record", "."], ja: "彼女はレースに勝っただけでなく、記録も更新しました。" },

    // --- Additional sentences (added in expansion pass) ---
    { level: 5, tokens: ["We", "are", "good", "friends", "."], ja: "私たちは良い友達です。" },
    { level: 5, tokens: ["I", "like", "reading", "books", "."], ja: "私は本を読むことが好きです。" },
    { level: 4, tokens: ["I", "will", "visit", "my", "grandmother", "tomorrow", "."], ja: "私は明日祖母を訪ねます。" },
    { level: 4, tokens: ["She", "is", "good", "at", "cooking", "."], ja: "彼女は料理が得意です。" },
    { level: 3, tokens: ["I", "have", "never", "been", "to", "Okinawa", "."], ja: "私は沖縄に行ったことがありません。" },
    { level: 3, tokens: ["While", "I", "was", "studying", ",", "my", "phone", "rang", "."], ja: "勉強している間に、電話が鳴りました。" },
    { level: 2, tokens: ["Whoever", "wins", "the", "contest", "will", "receive", "a", "prize", "."], ja: "コンテストで勝った人は誰でも賞をもらいます。" },
    { level: 2, tokens: ["No", "sooner", "had", "he", "arrived", "than", "it", "started", "to", "rain", "."], ja: "彼が到着するとすぐに雨が降り始めました。" },

    // --- Expansion batch 2 (Eiken 5) ---
    { level: 5, tokens: ["My", "father", "is", "a", "doctor", "."], ja: "私の父は医者です。" },
    { level: 5, tokens: ["We", "have", "two", "cats", "."], ja: "私たちは猫を二匹飼っています。" },
    { level: 5, tokens: ["I", "go", "to", "school", "by", "bus", "."], ja: "私はバスで学校に行きます。" },
    { level: 5, tokens: ["She", "can", "swim", "very", "well", "."], ja: "彼女はとても上手に泳げます。" },
    { level: 5, tokens: ["Is", "this", "your", "bag", "?"], ja: "これはあなたのかばんですか。" },
    { level: 5, tokens: ["He", "watches", "TV", "every", "night", "."], ja: "彼は毎晩テレビを見ます。" },
    { level: 5, tokens: ["I", "have", "a", "red", "pen", "."], ja: "私は赤いペンを持っています。" },
    { level: 5, tokens: ["We", "are", "in", "the", "same", "class", "."], ja: "私たちは同じクラスです。" },
    { level: 5, tokens: ["My", "mother", "cooks", "dinner", "every", "day", "."], ja: "私の母は毎日夕食を作ります。" },
    { level: 5, tokens: ["The", "cat", "is", "under", "the", "table", "."], ja: "猫はテーブルの下にいます。" },
    { level: 5, tokens: ["I", "wake", "up", "at", "seven", "."], ja: "私は7時に起きます。" },
    { level: 5, tokens: ["She", "has", "long", "hair", "."], ja: "彼女は髪が長いです。" },
    { level: 5, tokens: ["Let's", "go", "to", "the", "park", "."], ja: "公園に行きましょう。" },
    { level: 5, tokens: ["He", "is", "very", "kind", "."], ja: "彼はとても親切です。" },
    { level: 5, tokens: ["I", "don't", "like", "coffee", "."], ja: "私はコーヒーが好きではありません。" },
    { level: 5, tokens: ["What", "is", "your", "favorite", "color", "?"], ja: "あなたの好きな色は何ですか。" },
    { level: 5, tokens: ["My", "birthday", "is", "in", "May", "."], ja: "私の誕生日は5月です。" },
    { level: 5, tokens: ["They", "are", "playing", "in", "the", "garden", "."], ja: "彼らは庭で遊んでいます。" },
    { level: 5, tokens: ["I", "usually", "walk", "to", "school", "."], ja: "私はたいてい歩いて学校に行きます。" },
    { level: 5, tokens: ["This", "soup", "is", "very", "hot", "."], ja: "このスープはとても熱いです。" },
    { level: 5, tokens: ["She", "is", "reading", "a", "book", "now", "."], ja: "彼女は今本を読んでいます。" },
    { level: 5, tokens: ["We", "go", "shopping", "on", "weekends", "."], ja: "私たちは週末に買い物に行きます。" },
    { level: 5, tokens: ["I", "have", "three", "brothers", "."], ja: "私には兄弟が三人います。" },
    { level: 5, tokens: ["He", "runs", "fast", "."], ja: "彼は速く走ります。" },

    // --- Expansion batch 2 (Eiken 4) ---
    { level: 4, tokens: ["I", "have", "never", "eaten", "sushi", "."], ja: "私は寿司を食べたことがありません。" },
    { level: 4, tokens: ["She", "is", "going", "to", "visit", "Kyoto", "next", "week", "."], ja: "彼女は来週京都を訪れる予定です。" },
    { level: 4, tokens: ["I", "must", "finish", "my", "homework", "today", "."], ja: "私は今日宿題を終えなければなりません。" },
    { level: 4, tokens: ["He", "doesn't", "have", "to", "work", "on", "Sundays", "."], ja: "彼は日曜日に働く必要はありません。" },
    { level: 4, tokens: ["What", "are", "you", "going", "to", "do", "this", "weekend", "?"], ja: "今週末は何をする予定ですか。" },
    { level: 4, tokens: ["I", "was", "born", "in", "Osaka", "."], ja: "私は大阪で生まれました。" },
    { level: 4, tokens: ["She", "speaks", "English", "very", "well", "."], ja: "彼女はとても上手に英語を話します。" },
    { level: 4, tokens: ["We", "should", "leave", "now", "."], ja: "私たちは今出発するべきです。" },
    { level: 4, tokens: ["He", "is", "taller", "than", "his", "brother", "."], ja: "彼は彼の兄より背が高いです。" },
    { level: 4, tokens: ["I", "would", "like", "a", "cup", "of", "tea", "."], ja: "お茶を一杯いただきたいです。" },
    { level: 4, tokens: ["She", "is", "learning", "how", "to", "drive", "."], ja: "彼女は運転の仕方を習っています。" },
    { level: 4, tokens: ["My", "sister", "is", "interested", "in", "art", "."], ja: "私の妹は美術に興味があります。" },
    { level: 4, tokens: ["We", "are", "looking", "forward", "to", "the", "trip", "."], ja: "私たちはその旅行を楽しみにしています。" },
    { level: 4, tokens: ["I", "have", "to", "study", "for", "the", "test", "."], ja: "私はそのテストのために勉強しなければなりません。" },
    { level: 4, tokens: ["He", "asked", "me", "a", "question", "."], ja: "彼は私に質問をしました。" },
    { level: 4, tokens: ["She", "was", "surprised", "at", "the", "news", "."], ja: "彼女はそのニュースに驚きました。" },
    { level: 4, tokens: ["I", "need", "to", "buy", "some", "milk", "."], ja: "私は牛乳を買う必要があります。" },
    { level: 4, tokens: ["They", "moved", "to", "a", "new", "house", "last", "month", "."], ja: "彼らは先月新しい家に引っ越しました。" },
    { level: 4, tokens: ["He", "is", "afraid", "of", "dogs", "."], ja: "彼は犬を怖がっています。" },
    { level: 4, tokens: ["I", "will", "call", "you", "later", "."], ja: "後であなたに電話します。" },

    // --- Expansion batch 2 (Eiken 3) ---
    { level: 3, tokens: ["I", "didn't", "know", "what", "to", "say", "."], ja: "私は何と言えばいいかわかりませんでした。" },
    { level: 3, tokens: ["She", "told", "me", "that", "she", "was", "tired", "."], ja: "彼女は私に疲れていると言いました。" },
    { level: 3, tokens: ["He", "has", "been", "studying", "English", "for", "three", "years", "."], ja: "彼は3年間英語を勉強し続けています。" },
    { level: 3, tokens: ["I", "want", "you", "to", "help", "me", "with", "this", "."], ja: "これを手伝ってほしいです。" },
    { level: 3, tokens: ["Although", "he", "is", "young", ",", "he", "is", "very", "wise", "."], ja: "彼は若いけれど、とても賢いです。" },
    { level: 3, tokens: ["This", "is", "the", "book", "which", "she", "wrote", "."], ja: "これは彼女が書いた本です。" },
    { level: 3, tokens: ["I", "am", "looking", "forward", "to", "seeing", "you", "."], ja: "あなたに会えるのを楽しみにしています。" },
    { level: 3, tokens: ["He", "stopped", "to", "buy", "some", "bread", "."], ja: "彼はパンを買うために立ち止まりました。" },
    { level: 3, tokens: ["I", "remember", "meeting", "her", "at", "the", "party", "."], ja: "私はそのパーティーで彼女に会ったことを覚えています。" },
    { level: 3, tokens: ["The", "movie", "was", "so", "boring", "that", "I", "fell", "asleep", "."], ja: "その映画はとても退屈だったので、私は眠ってしまいました。" },
    { level: 3, tokens: ["She", "asked", "me", "where", "I", "lived", "."], ja: "彼女は私にどこに住んでいるか尋ねました。" },
    { level: 3, tokens: ["I", "was", "born", "and", "raised", "in", "Tokyo", "."], ja: "私は東京で生まれ育ちました。" },
    { level: 3, tokens: ["He", "gave", "up", "trying", "to", "fix", "it", "."], ja: "彼はそれを直そうとするのをあきらめました。" },
    { level: 3, tokens: ["I", "would", "rather", "stay", "home", "than", "go", "out", "."], ja: "私は出かけるよりも家にいたいです。" },
    { level: 3, tokens: ["She", "is", "used", "to", "living", "alone", "."], ja: "彼女は一人暮らしに慣れています。" },
    { level: 3, tokens: ["It", "took", "me", "an", "hour", "to", "finish", "the", "report", "."], ja: "そのレポートを終えるのに1時間かかりました。" },

    // --- Expansion batch 2 (Eiken Pre-2 / 2) ---
    { level: 2, tokens: ["Had", "I", "known", "about", "the", "meeting", ",", "I", "would", "have", "attended", "."], ja: "その会議について知っていたら、出席していたでしょう。" },
    { level: 2, tokens: ["The", "manager", "insisted", "that", "the", "report", "be", "submitted", "by", "Friday", "."], ja: "部長はその報告書が金曜日までに提出されるべきだと主張しました。" },
    { level: 2, tokens: ["She", "would", "have", "passed", "the", "exam", "if", "she", "had", "studied", "harder", "."], ja: "もっと一生懸命勉強していたら、彼女は試験に合格していたでしょう。" },
    { level: 2, tokens: ["Hardly", "had", "the", "train", "left", "when", "it", "began", "to", "snow", "."], ja: "電車が出発するとすぐに雪が降り始めました。" },
    { level: 2, tokens: ["The", "report", "needs", "to", "be", "finished", "by", "tomorrow", "morning", "."], ja: "その報告書は明日の朝までに終わらせる必要があります。" },
    { level: 2, tokens: ["Given", "the", "circumstances", ",", "I", "think", "we", "made", "the", "right", "decision", "."], ja: "状況を考えると、私たちは正しい決断をしたと思います。" },
    { level: 2, tokens: ["It", "was", "not", "until", "I", "left", "home", "that", "I", "realized", "how", "important", "family", "is", "."], ja: "家を出て初めて、家族がどれほど大切か気づきました。" },
    { level: 2, tokens: ["The", "more", "carefully", "you", "plan", ",", "the", "less", "likely", "you", "are", "to", "fail", "."], ja: "慎重に計画すればするほど、失敗しにくくなります。" },
    { level: 2, tokens: ["I", "have", "no", "choice", "but", "to", "accept", "the", "offer", "."], ja: "その申し出を受け入れるしかありません。" },
    { level: 2, tokens: ["She", "is", "said", "to", "have", "studied", "abroad", "when", "she", "was", "young", "."], ja: "彼女は若い頃留学していたと言われています。" },

    // --- Expansion batch 3 (Eiken 5) ---
    { level: 5, tokens: ["This", "is", "my", "favorite", "song", "."], ja: "これは私のお気に入りの歌です。" },
    { level: 5, tokens: ["My", "brother", "likes", "baseball", "very", "much", "."], ja: "私の兄は野球がとても好きです。" },
    { level: 5, tokens: ["I", "clean", "my", "room", "every", "Saturday", "."], ja: "私は毎週土曜日に部屋を掃除します。" },
    { level: 5, tokens: ["She", "draws", "pictures", "after", "school", "."], ja: "彼女は放課後に絵を描きます。" },
    { level: 5, tokens: ["Where", "do", "you", "live", "?"], ja: "あなたはどこに住んでいますか。" },
    { level: 5, tokens: ["I", "have", "lunch", "with", "my", "friends", "."], ja: "私は友達と昼食を食べます。" },
    { level: 5, tokens: ["He", "is", "good", "at", "math", "."], ja: "彼は数学が得意です。" },
    { level: 5, tokens: ["We", "study", "English", "on", "Mondays", "."], ja: "私たちは月曜日に英語を勉強します。" },
    { level: 5, tokens: ["I", "have", "a", "small", "dog", "."], ja: "私は小さい犬を飼っています。" },
    { level: 5, tokens: ["She", "always", "smiles", "."], ja: "彼女はいつも笑顔です。" },
    { level: 5, tokens: ["My", "favorite", "subject", "is", "science", "."], ja: "私の好きな科目は理科です。" },
    { level: 5, tokens: ["Can", "I", "use", "your", "pen", "?"], ja: "あなたのペンを使ってもいいですか。" },
    { level: 5, tokens: ["I", "like", "summer", "the", "best", "."], ja: "私は夏が一番好きです。" },
    { level: 5, tokens: ["He", "comes", "home", "at", "six", "."], ja: "彼は6時に帰宅します。" },
    { level: 5, tokens: ["This", "cake", "looks", "delicious", "."], ja: "このケーキはおいしそうです。" },
    { level: 5, tokens: ["I", "always", "drink", "water", "in", "the", "morning", "."], ja: "私はいつも朝に水を飲みます。" },
    { level: 5, tokens: ["She", "is", "wearing", "a", "blue", "dress", "."], ja: "彼女は青いドレスを着ています。" },
    { level: 5, tokens: ["My", "school", "starts", "at", "eight", "thirty", "."], ja: "私の学校は8時30分に始まります。" },

    // --- Expansion batch 3 (Eiken 4) ---
    { level: 4, tokens: ["I", "am", "planning", "to", "study", "abroad", "next", "year", "."], ja: "私は来年留学する予定です。" },
    { level: 4, tokens: ["She", "has", "to", "wake", "up", "early", "tomorrow", "."], ja: "彼女は明日早起きしなければなりません。" },
    { level: 4, tokens: ["He", "enjoys", "playing", "video", "games", "with", "his", "friends", "."], ja: "彼は友達とテレビゲームをするのを楽しみます。" },
    { level: 4, tokens: ["I", "forgot", "to", "bring", "my", "umbrella", "."], ja: "私は傘を持ってくるのを忘れました。" },
    { level: 4, tokens: ["She", "decided", "to", "join", "the", "tennis", "club", "."], ja: "彼女はテニス部に入ることに決めました。" },
    { level: 4, tokens: ["We", "had", "a", "great", "time", "at", "the", "festival", "."], ja: "私たちはお祭りで楽しい時間を過ごしました。" },
    { level: 4, tokens: ["I", "am", "not", "good", "at", "singing", "."], ja: "私は歌うのが得意ではありません。" },
    { level: 4, tokens: ["He", "finished", "his", "homework", "before", "dinner", "."], ja: "彼は夕食の前に宿題を終えました。" },
    { level: 4, tokens: ["She", "is", "proud", "of", "her", "team", "."], ja: "彼女は自分のチームを誇りに思っています。" },
    { level: 4, tokens: ["I", "think", "this", "movie", "is", "exciting", "."], ja: "私はこの映画はわくわくすると思います。" },
    { level: 4, tokens: ["He", "always", "helps", "his", "classmates", "."], ja: "彼はいつもクラスメートを助けます。" },
    { level: 4, tokens: ["We", "are", "planning", "a", "surprise", "party", "."], ja: "私たちはサプライズパーティーを計画しています。" },
    { level: 4, tokens: ["She", "practices", "the", "piano", "every", "evening", "."], ja: "彼女は毎晩ピアノを練習します。" },
    { level: 4, tokens: ["I", "am", "sure", "she", "will", "succeed", "."], ja: "彼女はきっと成功すると思います。" },
    { level: 4, tokens: ["He", "apologized", "for", "being", "late", "."], ja: "彼は遅刻したことを謝りました。" },
    { level: 4, tokens: ["I", "borrowed", "this", "book", "from", "the", "library", "."], ja: "私はこの本を図書館で借りました。" },
    { level: 4, tokens: ["She", "is", "worried", "about", "the", "exam", "."], ja: "彼女はその試験について心配しています。" },
    { level: 4, tokens: ["He", "promised", "to", "call", "me", "tonight", "."], ja: "彼は今夜電話すると約束しました。" },

    // --- Expansion batch 3 (Eiken 3) ---
    { level: 3, tokens: ["I", "was", "so", "nervous", "that", "I", "couldn't", "speak", "."], ja: "私はとても緊張して話せませんでした。" },
    { level: 3, tokens: ["She", "kept", "working", "even", "though", "she", "was", "exhausted", "."], ja: "彼女は疲れ果てていたけれど働き続けました。" },
    { level: 3, tokens: ["He", "is", "the", "only", "student", "who", "passed", "the", "test", "."], ja: "彼はそのテストに合格した唯一の生徒です。" },
    { level: 3, tokens: ["I", "had", "already", "left", "when", "she", "called", "."], ja: "彼女が電話したとき、私はすでに出発していました。" },
    { level: 3, tokens: ["This", "is", "the", "place", "where", "we", "first", "met", "."], ja: "ここは私たちが初めて出会った場所です。" },
    { level: 3, tokens: ["He", "speaks", "not", "only", "English", "but", "also", "French", "."], ja: "彼は英語だけでなくフランス語も話します。" },
    { level: 3, tokens: ["I", "am", "trying", "to", "improve", "my", "writing", "skills", "."], ja: "私は文章力を向上させようとしています。" },
    { level: 3, tokens: ["She", "felt", "relieved", "after", "finishing", "the", "project", "."], ja: "彼女はそのプロジェクトを終えてほっとしました。" },
    { level: 3, tokens: ["I", "couldn't", "help", "laughing", "at", "his", "joke", "."], ja: "私は彼の冗談に笑わずにいられませんでした。" },
    { level: 3, tokens: ["He", "made", "an", "effort", "to", "arrive", "on", "time", "."], ja: "彼は時間通りに来るよう努力しました。" },
    { level: 3, tokens: ["I", "have", "not", "decided", "what", "to", "do", "yet", "."], ja: "私はまだ何をするか決めていません。" },
    { level: 3, tokens: ["She", "looked", "as", "if", "she", "had", "seen", "a", "ghost", "."], ja: "彼女はまるで幽霊を見たかのような顔をしていました。" },
    { level: 3, tokens: ["The", "more", "I", "learn", ",", "the", "more", "I", "want", "to", "know", "."], ja: "学べば学ぶほど、もっと知りたくなります。" },
    { level: 3, tokens: ["He", "is", "responsible", "for", "managing", "the", "team", "."], ja: "彼はチームを管理する責任があります。" },

    // --- Expansion batch 3 (Eiken Pre-2 / 2) ---
    { level: 2, tokens: ["Were", "it", "not", "for", "your", "help", ",", "I", "would", "have", "failed", "."], ja: "あなたの助けがなければ、私は失敗していたでしょう。" },
    { level: 2, tokens: ["The", "committee", "recommended", "that", "the", "policy", "be", "reviewed", "immediately", "."], ja: "委員会はその方針が直ちに見直されるべきだと勧告しました。" },
    { level: 2, tokens: ["She", "must", "have", "forgotten", "about", "our", "appointment", "."], ja: "彼女は私たちの約束を忘れてしまったに違いありません。" },
    { level: 2, tokens: ["Not", "until", "he", "apologized", "did", "she", "forgive", "him", "."], ja: "彼が謝るまで、彼女は彼を許しませんでした。" },
    { level: 2, tokens: ["The", "plan", "is", "likely", "to", "be", "postponed", "due", "to", "the", "weather", "."], ja: "その計画は天候のため延期される可能性が高いです。" },
    { level: 2, tokens: ["Considering", "her", "age", ",", "she", "performed", "remarkably", "well", "."], ja: "彼女の年齢を考えると、驚くほど良い成績を出しました。" },
    { level: 2, tokens: ["It", "is", "essential", "that", "every", "employee", "follow", "the", "safety", "rules", "."], ja: "すべての従業員が安全規則に従うことが不可欠です。" },
    { level: 2, tokens: ["No", "matter", "how", "hard", "I", "tried", ",", "I", "could", "not", "solve", "the", "puzzle", "."], ja: "どんなに頑張っても、私はそのパズルを解けませんでした。" },
    { level: 2, tokens: ["I", "would", "appreciate", "it", "if", "you", "could", "reply", "as", "soon", "as", "possible", "."], ja: "できるだけ早くご返信いただければ幸いです。" },
    { level: 2, tokens: ["She", "is", "known", "for", "having", "donated", "a", "large", "sum", "to", "charity", "."], ja: "彼女は慈善団体に多額の寄付をしたことで知られています。" },

    // --- Expansion batch 4 (Eiken 5) ---
    { level: 5, tokens: ["I", "have", "a", "new", "bike", "."], ja: "私は新しい自転車を持っています。" },
    { level: 5, tokens: ["She", "is", "from", "Canada", "."], ja: "彼女はカナダ出身です。" },
    { level: 5, tokens: ["We", "play", "basketball", "after", "school", "."], ja: "私たちは放課後にバスケットボールをします。" },
    { level: 5, tokens: ["He", "has", "a", "big", "family", "."], ja: "彼は大家族です。" },
    { level: 5, tokens: ["I", "drink", "milk", "every", "morning", "."], ja: "私は毎朝牛乳を飲みます。" },
    { level: 5, tokens: ["This", "flower", "is", "very", "beautiful", "."], ja: "この花はとても美しいです。" },
    { level: 5, tokens: ["She", "cleans", "her", "room", "on", "Sundays", "."], ja: "彼女は日曜日に部屋を掃除します。" },
    { level: 5, tokens: ["I", "can", "play", "the", "guitar", "."], ja: "私はギターを弾くことができます。" },
    { level: 5, tokens: ["He", "is", "in", "the", "soccer", "club", "."], ja: "彼はサッカー部に入っています。" },
    { level: 5, tokens: ["We", "went", "to", "the", "zoo", "last", "week", "."], ja: "私たちは先週動物園に行きました。" },
    { level: 5, tokens: ["I", "have", "a", "lot", "of", "homework", "today", "."], ja: "私は今日宿題がたくさんあります。" },
    { level: 5, tokens: ["She", "likes", "winter", "more", "than", "summer", "."], ja: "彼女は夏より冬が好きです。" },
    { level: 5, tokens: ["My", "father", "works", "at", "a", "bank", "."], ja: "私の父は銀行で働いています。" },
    { level: 5, tokens: ["I", "go", "to", "bed", "at", "ten", "."], ja: "私は10時に寝ます。" },
    { level: 5, tokens: ["He", "is", "a", "fast", "runner", "."], ja: "彼は足が速いです。" },
    { level: 5, tokens: ["This", "is", "a", "nice", "park", "."], ja: "これは素敵な公園です。" },

    // --- Expansion batch 4 (Eiken 4) ---
    { level: 4, tokens: ["She", "is", "interested", "in", "studying", "abroad", "."], ja: "彼女は留学することに興味があります。" },
    { level: 4, tokens: ["I", "have", "already", "finished", "my", "homework", "."], ja: "私はもう宿題を終えました。" },
    { level: 4, tokens: ["He", "was", "late", "for", "school", "this", "morning", "."], ja: "彼は今朝学校に遅刻しました。" },
    { level: 4, tokens: ["We", "are", "going", "to", "have", "a", "test", "tomorrow", "."], ja: "私たちは明日テストがあります。" },
    { level: 4, tokens: ["She", "is", "kind", "to", "everyone", "."], ja: "彼女はみんなに親切です。" },
    { level: 4, tokens: ["I", "want", "to", "travel", "around", "the", "world", "."], ja: "私は世界中を旅行したいです。" },
    { level: 4, tokens: ["He", "was", "excited", "about", "the", "trip", "."], ja: "彼はその旅行にわくわくしていました。" },
    { level: 4, tokens: ["She", "lost", "her", "key", "yesterday", "."], ja: "彼女は昨日鍵をなくしました。" },
    { level: 4, tokens: ["I", "have", "to", "clean", "my", "room", "before", "dinner", "."], ja: "私は夕食前に部屋を掃除しなければなりません。" },
    { level: 4, tokens: ["He", "is", "planning", "to", "buy", "a", "new", "car", "."], ja: "彼は新しい車を買う予定です。" },
    { level: 4, tokens: ["We", "should", "be", "careful", "on", "the", "road", "."], ja: "私たちは道路で気をつけるべきです。" },
    { level: 4, tokens: ["She", "is", "going", "to", "cook", "dinner", "tonight", "."], ja: "彼女は今夜夕食を作る予定です。" },
    { level: 4, tokens: ["I", "was", "able", "to", "solve", "the", "problem", "."], ja: "私はその問題を解くことができました。" },
    { level: 4, tokens: ["He", "must", "be", "tired", "after", "the", "long", "trip", "."], ja: "彼は長旅の後で疲れているに違いありません。" },

    // --- Expansion batch 4 (Eiken 3) ---
    { level: 3, tokens: ["I", "have", "been", "waiting", "for", "you", "for", "an", "hour", "."], ja: "私はあなたを1時間待ち続けています。" },
    { level: 3, tokens: ["She", "was", "disappointed", "that", "she", "couldn't", "go", "."], ja: "彼女は行けなくてがっかりしました。" },
    { level: 3, tokens: ["He", "is", "the", "man", "whose", "car", "was", "stolen", "."], ja: "彼は車を盗まれた男性です。" },
    { level: 3, tokens: ["I", "will", "let", "you", "know", "as", "soon", "as", "I", "arrive", "."], ja: "到着したらすぐにお知らせします。" },
    { level: 3, tokens: ["She", "seems", "to", "be", "worried", "about", "something", "."], ja: "彼女は何かを心配しているようです。" },
    { level: 3, tokens: ["He", "spent", "the", "whole", "weekend", "cleaning", "the", "garage", "."], ja: "彼はガレージを掃除して週末をすべて過ごしました。" },
    { level: 3, tokens: ["I", "wish", "I", "could", "speak", "French", "fluently", "."], ja: "フランス語を流暢に話せたらいいのに。" },
    { level: 3, tokens: ["She", "managed", "to", "finish", "the", "marathon", "."], ja: "彼女は何とかマラソンを完走しました。" },
    { level: 3, tokens: ["He", "regrets", "not", "studying", "harder", "in", "high", "school", "."], ja: "彼は高校でもっと勉強しなかったことを後悔しています。" },
    { level: 3, tokens: ["I", "was", "told", "to", "wait", "outside", "the", "office", "."], ja: "私は事務所の外で待つように言われました。" },
    { level: 3, tokens: ["She", "is", "capable", "of", "handling", "difficult", "situations", "."], ja: "彼女は難しい状況に対処する能力があります。" },
    { level: 3, tokens: ["He", "ended", "up", "missing", "the", "last", "train", "."], ja: "彼は結局終電を逃してしまいました。" },

    // --- Expansion batch 4 (Eiken Pre-2 / 2) ---
    { level: 2, tokens: ["Scarcely", "had", "the", "game", "begun", "when", "it", "started", "to", "rain", "."], ja: "試合が始まるとすぐに雨が降り始めました。" },
    { level: 2, tokens: ["The", "experiment", "was", "conducted", "in", "order", "to", "test", "the", "new", "theory", "."], ja: "その実験は新しい理論を検証するために行われました。" },
    { level: 2, tokens: ["Were", "I", "in", "your", "position", ",", "I", "would", "accept", "the", "offer", "."], ja: "もし私があなたの立場なら、その申し出を受け入れるでしょう。" },
    { level: 2, tokens: ["It", "is", "widely", "believed", "that", "exercise", "improves", "mental", "health", "."], ja: "運動は精神的健康を向上させると広く信じられています。" },
    { level: 2, tokens: ["So", "exhausted", "was", "she", "that", "she", "fell", "asleep", "instantly", "."], ja: "彼女はとても疲れていたので、すぐに眠ってしまいました。" },
    { level: 2, tokens: ["The", "sooner", "you", "start", ",", "the", "easier", "it", "will", "be", "."], ja: "早く始めれば始めるほど、楽になります。" },
    { level: 2, tokens: ["He", "would", "rather", "have", "stayed", "home", "than", "attended", "the", "meeting", "."], ja: "彼は会議に出るより家にいたかったでしょう。" },
    { level: 2, tokens: ["It", "goes", "without", "saying", "that", "honesty", "is", "important", "."], ja: "正直であることが重要なのは言うまでもありません。" },

    // --- Expansion batch 5 (Eiken 5) ---
    { level: 5, tokens: ["I", "have", "two", "sisters", "."], ja: "私には姉妹が二人います。" },
    { level: 5, tokens: ["She", "plays", "the", "violin", "."], ja: "彼女はバイオリンを弾きます。" },
    { level: 5, tokens: ["We", "eat", "rice", "every", "day", "."], ja: "私たちは毎日米を食べます。" },
    { level: 5, tokens: ["He", "is", "my", "best", "friend", "."], ja: "彼は私の親友です。" },
    { level: 5, tokens: ["I", "like", "to", "draw", "pictures", "."], ja: "私は絵を描くのが好きです。" },
    { level: 5, tokens: ["This", "is", "a", "very", "old", "temple", "."], ja: "これはとても古いお寺です。" },
    { level: 5, tokens: ["She", "has", "a", "white", "cat", "."], ja: "彼女は白い猫を飼っています。" },
    { level: 5, tokens: ["I", "study", "English", "every", "day", "."], ja: "私は毎日英語を勉強します。" },
    { level: 5, tokens: ["He", "is", "wearing", "glasses", "."], ja: "彼はめがねをかけています。" },
    { level: 5, tokens: ["We", "have", "music", "class", "on", "Fridays", "."], ja: "私たちは金曜日に音楽の授業があります。" },
    { level: 5, tokens: ["I", "feel", "happy", "today", "."], ja: "私は今日幸せに感じます。" },
    { level: 5, tokens: ["She", "is", "talking", "with", "her", "teacher", "."], ja: "彼女は先生と話しています。" },
    { level: 5, tokens: ["My", "uncle", "lives", "in", "Tokyo", "."], ja: "私のおじは東京に住んでいます。" },
    { level: 5, tokens: ["I", "want", "a", "new", "bag", "."], ja: "私は新しいかばんが欲しいです。" },
    { level: 5, tokens: ["He", "always", "wakes", "up", "early", "."], ja: "彼はいつも早く起きます。" },
    { level: 5, tokens: ["This", "is", "a", "very", "important", "test", "."], ja: "これはとても大切なテストです。" },

    // --- Expansion batch 5 (Eiken 4) ---
    { level: 4, tokens: ["He", "is", "good", "at", "playing", "the", "piano", "."], ja: "彼はピアノを弾くのが得意です。" },
    { level: 4, tokens: ["I", "was", "happy", "to", "hear", "the", "good", "news", "."], ja: "私はその良い知らせを聞いてうれしかったです。" },
    { level: 4, tokens: ["She", "is", "going", "to", "meet", "her", "friend", "tomorrow", "."], ja: "彼女は明日友達に会う予定です。" },
    { level: 4, tokens: ["We", "need", "to", "be", "quiet", "in", "the", "library", "."], ja: "私たちは図書館では静かにする必要があります。" },
    { level: 4, tokens: ["He", "is", "different", "from", "his", "brother", "."], ja: "彼は兄とは違います。" },
    { level: 4, tokens: ["I", "have", "to", "return", "this", "book", "today", "."], ja: "私は今日この本を返さなければなりません。" },
    { level: 4, tokens: ["She", "was", "born", "in", "a", "small", "town", "."], ja: "彼女は小さな町で生まれました。" },
    { level: 4, tokens: ["He", "is", "thinking", "about", "his", "future", "."], ja: "彼は将来について考えています。" },
    { level: 4, tokens: ["I", "am", "going", "to", "join", "a", "new", "club", "."], ja: "私は新しいクラブに入る予定です。" },
    { level: 4, tokens: ["She", "always", "does", "her", "best", "."], ja: "彼女はいつも最善を尽くします。" },
    { level: 4, tokens: ["He", "needs", "more", "time", "to", "finish", "the", "work", "."], ja: "彼はその仕事を終えるのにもっと時間が必要です。" },
    { level: 4, tokens: ["I", "am", "afraid", "I", "will", "be", "late", "."], ja: "私は遅刻するのではないかと心配です。" },
    { level: 4, tokens: ["She", "is", "interested", "in", "Japanese", "culture", "."], ja: "彼女は日本の文化に興味があります。" },
    { level: 4, tokens: ["He", "tried", "his", "best", "but", "failed", "."], ja: "彼は最善を尽くしましたが失敗しました。" },

    // --- Expansion batch 5 (Eiken 3) ---
    { level: 3, tokens: ["I", "have", "been", "thinking", "about", "changing", "jobs", "."], ja: "私は転職について考え続けています。" },
    { level: 3, tokens: ["She", "was", "afraid", "of", "making", "a", "mistake", "."], ja: "彼女は間違えることを恐れていました。" },
    { level: 3, tokens: ["This", "is", "a", "device", "that", "helps", "people", "communicate", "."], ja: "これは人々のコミュニケーションを助ける機器です。" },
    { level: 3, tokens: ["I", "was", "surprised", "to", "find", "out", "the", "truth", "."], ja: "私はその真実を知って驚きました。" },
    { level: 3, tokens: ["He", "is", "trying", "his", "best", "to", "overcome", "his", "fear", "."], ja: "彼は恐怖を克服しようと最善を尽くしています。" },
    { level: 3, tokens: ["She", "is", "not", "as", "shy", "as", "she", "used", "to", "be", "."], ja: "彼女は以前ほど内気ではありません。" },
    { level: 3, tokens: ["I", "can't", "believe", "how", "fast", "time", "goes", "."], ja: "時がどれほど速く過ぎるか信じられません。" },
    { level: 3, tokens: ["He", "was", "praised", "for", "his", "hard", "work", "."], ja: "彼は努力を称賛されました。" },
    { level: 3, tokens: ["She", "has", "decided", "to", "pursue", "a", "career", "in", "medicine", "."], ja: "彼女は医学の道に進むことを決めました。" },
    { level: 3, tokens: ["I", "just", "found", "out", "that", "the", "store", "is", "closed", "today", "."], ja: "今日その店が閉まっていることがわかったばかりです。" },
    { level: 3, tokens: ["He", "is", "not", "the", "type", "of", "person", "who", "gives", "up", "easily", "."], ja: "彼は簡単にあきらめるタイプの人ではありません。" },
    { level: 3, tokens: ["I", "didn't", "expect", "to", "see", "you", "here", "."], ja: "ここであなたに会うとは思いませんでした。" },

    // --- Expansion batch 5 (Eiken Pre-2 / 2) ---
    { level: 2, tokens: ["Such", "was", "the", "impact", "of", "the", "speech", "that", "everyone", "applauded", "."], ja: "そのスピーチの影響はとても大きく、誰もが拍手しました。" },
    { level: 2, tokens: ["The", "data", "suggests", "that", "consumer", "habits", "are", "changing", "rapidly", "."], ja: "そのデータは消費者の習慣が急速に変化していることを示唆しています。" },
    { level: 2, tokens: ["Little", "did", "they", "know", "that", "the", "plan", "would", "fail", "."], ja: "その計画が失敗するとは彼らはほとんど知りませんでした。" },
    { level: 2, tokens: ["I", "can't", "afford", "to", "waste", "any", "more", "time", "on", "this", "."], ja: "これにこれ以上時間を無駄にする余裕はありません。" },
    { level: 2, tokens: ["What", "matters", "most", "is", "that", "everyone", "stays", "safe", "."], ja: "最も重要なのは皆が安全でいることです。" },
    { level: 2, tokens: ["Provided", "that", "you", "follow", "the", "instructions", ",", "you", "will", "succeed", "."], ja: "指示に従いさえすれば、あなたは成功するでしょう。" },
    { level: 2, tokens: ["As", "far", "as", "I", "know", ",", "the", "meeting", "has", "been", "canceled", "."], ja: "私の知る限り、その会議は中止されました。" },
    { level: 2, tokens: ["The", "longer", "the", "delay", "lasted", ",", "the", "more", "frustrated", "the", "passengers", "became", "."], ja: "遅延が長引くほど、乗客はより苛立ちました。" }
  ];

  global.EQ_CONTENT = { UNITS: UNITS, SENTENCES: SENTENCES };
})(window);
