/* ============================================================
   English Quest — Content Data
   Eiken 5級 → 2級 level vocabulary & sentence patterns
   Edit this file to add/change words, units, or questions.

   NOTE ON SCOPE: this is an expanded version (roughly 3-4x the
   original word counts), extending each category up through
   Eiken Pre-2 / 2 level vocabulary. Reaching 500+ words per
   category is a much larger project intended to continue across
   future editing sessions — see PROJECT_SUMMARY.md.
   ============================================================ */
(function (global) {
  "use strict";

  // ---- Units (themed word groups, Eiken 5級 -> 2級 difficulty) ----
  var UNITS = [
    {
      id: "school",
      name: "School Life",
      emoji: "🏫",
      level: 5,
      words: [
        { en: "student", ja: "生徒" },
        { en: "teacher", ja: "先生" },
        { en: "classroom", ja: "教室" },
        { en: "textbook", ja: "教科書" },
        { en: "notebook", ja: "ノート" },
        { en: "pencil", ja: "鉛筆" },
        { en: "eraser", ja: "消しゴム" },
        { en: "homework", ja: "宿題" },
        { en: "test", ja: "テスト" },
        { en: "library", ja: "図書館" },
        { en: "lunch", ja: "昼食" },
        { en: "friend", ja: "友達" },
        { en: "club", ja: "部活" },
        { en: "subject", ja: "教科" },
        { en: "schedule", ja: "時間割" },
        { en: "principal", ja: "校長先生" },
        { en: "classmate", ja: "クラスメート" },
        { en: "uniform", ja: "制服" },
        { en: "blackboard", ja: "黒板" },
        { en: "chalk", ja: "チョーク" },
        { en: "desk", ja: "机" },
        { en: "chair", ja: "椅子" },
        { en: "gym", ja: "体育館" },
        { en: "playground", ja: "校庭" },
        { en: "exam", ja: "試験" },
        { en: "grade", ja: "学年・成績" },
        { en: "graduation", ja: "卒業" },
        { en: "entrance ceremony", ja: "入学式" },
        { en: "vacation", ja: "休み" },
        { en: "absent", ja: "欠席の" },
        { en: "present (at school)", ja: "出席の" },
        { en: "rule", ja: "規則" },
        { en: "lesson", ja: "授業" },
        { en: "score", ja: "点数" },
        { en: "report card", ja: "通知表" },
        { en: "field trip", ja: "遠足" },
        { en: "school festival", ja: "学園祭" },
        { en: "dormitory", ja: "寮" },
        { en: "scholarship", ja: "奨学金" },
        { en: "curriculum", ja: "カリキュラム" },
        { en: "assignment", ja: "課題" },
        { en: "ruler", ja: "定規" },
        { en: "scissors", ja: "はさみ" },
        { en: "glue", ja: "のり" },
        { en: "backpack", ja: "リュック" },
        { en: "locker", ja: "ロッカー" },
        { en: "hallway", ja: "廊下" },
        { en: "stairs", ja: "階段" },
        { en: "cafeteria", ja: "食堂" },
        { en: "schoolyard", ja: "校庭" },
        { en: "bell", ja: "ベル" },
        { en: "term", ja: "学期" },
        { en: "semester", ja: "学期" },
        { en: "timetable", ja: "時間割" },
        { en: "attendance", ja: "出席" },
        { en: "tardy", ja: "遅刻した" },
        { en: "detention", ja: "居残り" },
        { en: "punishment", ja: "罰" },
        { en: "praise", ja: "褒めること" },
        { en: "achievement", ja: "達成" },
        { en: "ability", ja: "能力" },
        { en: "effort", ja: "努力" },
        { en: "improve", ja: "上達する" },
        { en: "review", ja: "復習する" },
        { en: "preview", ja: "予習する" },
        { en: "memorize", ja: "暗記する" },
        { en: "understand", ja: "理解する" },
        { en: "explain", ja: "説明する" },
        { en: "answer", ja: "答える" },
        { en: "question", ja: "質問" },
        { en: "raise (a hand)", ja: "（手を）挙げる" },
        { en: "discuss", ja: "話し合う" },
        { en: "presentation", ja: "発表" },
        { en: "speech", ja: "スピーチ" },
        { en: "essay", ja: "作文" },
        { en: "composition", ja: "作文" },
        { en: "grammar", ja: "文法" },
        { en: "vocabulary", ja: "語彙" },
        { en: "spelling", ja: "つづり" },
        { en: "pronunciation", ja: "発音" },
        { en: "translate", ja: "翻訳する" },
        { en: "dictionary", ja: "辞書" },
        { en: "calculator", ja: "電卓" },
        { en: "experiment", ja: "実験" },
        { en: "laboratory", ja: "実験室" },
        { en: "microscope", ja: "顕微鏡" },
        { en: "equation", ja: "方程式" },
        { en: "geometry", ja: "幾何学" },
        { en: "history (subject)", ja: "歴史" },
        { en: "geography", ja: "地理" },
        { en: "science", ja: "理科" },
        { en: "mathematics", ja: "数学" },
        { en: "physical education", ja: "体育" },
        { en: "art class", ja: "美術" },
        { en: "music class", ja: "音楽" },
        { en: "moral education", ja: "道徳" },
        { en: "elective", ja: "選択科目" },
        { en: "required course", ja: "必修科目" },
        { en: "credit (academic)", ja: "単位" },
        { en: "diploma", ja: "卒業証書" },
        { en: "certificate", ja: "証明書" },
        { en: "enroll", ja: "入学する" },
        { en: "admission", ja: "入学" },
        { en: "tuition", ja: "授業料" },
        { en: "campus", ja: "キャンパス" },
        { en: "faculty", ja: "教職員" },
        { en: "counselor", ja: "カウンセラー" },
        { en: "nurse's office", ja: "保健室" },
        { en: "PTA", ja: "保護者会" },
        { en: "homeroom", ja: "ホームルーム" },
        { en: "transfer student", ja: "転校生" },
        { en: "exchange student", ja: "交換留学生" },
        { en: "study abroad", ja: "留学する" },
        { en: "self-study", ja: "自習" },
        { en: "cram school", ja: "塾" },
        { en: "tutor", ja: "家庭教師" },
        { en: "academic", ja: "学業の" },
        { en: "diligent", ja: "勤勉な" },
        { en: "lazy", ja: "怠惰な" },
        { en: "cheat (on a test)", ja: "カンニングする" },
        { en: "honest", ja: "正直な" },
        { en: "responsible", ja: "責任感のある" },
        { en: "punctuality", ja: "時間厳守" },
        { en: "cooperation", ja: "協力" },
        { en: "leadership", ja: "リーダーシップ" },
        { en: "committee", ja: "委員会" },
        { en: "representative", ja: "代表" },
        { en: "election (class)", ja: "選挙" },
        { en: "volunteer work", ja: "ボランティア活動" }
      ]
    },
    {
      id: "family",
      name: "Family & People",
      emoji: "👨‍👩‍👧‍👦",
      level: 5,
      words: [
        { en: "mother", ja: "母" },
        { en: "father", ja: "父" },
        { en: "sister", ja: "姉・妹" },
        { en: "brother", ja: "兄・弟" },
        { en: "grandmother", ja: "祖母" },
        { en: "grandfather", ja: "祖父" },
        { en: "family", ja: "家族" },
        { en: "baby", ja: "赤ちゃん" },
        { en: "uncle", ja: "おじ" },
        { en: "aunt", ja: "おば" },
        { en: "cousin", ja: "いとこ" },
        { en: "parents", ja: "両親" },
        { en: "husband", ja: "夫" },
        { en: "wife", ja: "妻" },
        { en: "son", ja: "息子" },
        { en: "daughter", ja: "娘" },
        { en: "nephew", ja: "甥" },
        { en: "niece", ja: "姪" },
        { en: "relative", ja: "親戚" },
        { en: "neighbor", ja: "隣人" },
        { en: "stranger", ja: "見知らぬ人" },
        { en: "adult", ja: "大人" },
        { en: "child", ja: "子ども" },
        { en: "elderly", ja: "高齢の" },
        { en: "twin", ja: "双子" },
        { en: "only child", ja: "一人っ子" },
        { en: "single parent", ja: "片親" },
        { en: "guardian", ja: "保護者" },
        { en: "ancestor", ja: "先祖" },
        { en: "generation", ja: "世代" },
        { en: "household", ja: "世帯" },
        { en: "marriage", ja: "結婚" },
        { en: "couple", ja: "夫婦・カップル" },
        { en: "stepfather", ja: "継父" },
        { en: "stepmother", ja: "継母" },
        { en: "infant", ja: "幼児" },
        { en: "toddler", ja: "よちよち歩きの子" },
        { en: "teenager", ja: "10代の若者" },
        { en: "youth", ja: "若者" },
        { en: "newborn", ja: "新生児" },
        { en: "pregnant", ja: "妊娠している" },
        { en: "raise (children)", ja: "育てる" },
        { en: "upbringing", ja: "しつけ" },
        { en: "discipline", ja: "しつけ・規律" },
        { en: "obey", ja: "従う" },
        { en: "spoil (a child)", ja: "甘やかす" },
        { en: "resemble", ja: "似ている" },
        { en: "personality", ja: "性格" },
        { en: "appearance", ja: "外見" },
        { en: "behavior", ja: "行動" },
        { en: "attitude", ja: "態度" },
        { en: "trust", ja: "信頼" },
        { en: "support (verb)", ja: "支える" },
        { en: "rely on", ja: "頼る" },
        { en: "argument", ja: "口論" },
        { en: "reconcile", ja: "仲直りする" },
        { en: "forgive", ja: "許す" },
        { en: "apologize", ja: "謝る" },
        { en: "comfort", ja: "慰める" },
        { en: "encourage", ja: "励ます" },
        { en: "advice", ja: "助言" },
        { en: "role model", ja: "お手本" },
        { en: "inherit", ja: "受け継ぐ" },
        { en: "heritage", ja: "遺産・伝統" },
        { en: "divorce", ja: "離婚" },
        { en: "separate (verb)", ja: "別れる" },
        { en: "engagement", ja: "婚約" },
        { en: "wedding", ja: "結婚式" },
        { en: "anniversary (family)", ja: "記念日" },
        { en: "in-law", ja: "義理の親族" },
        { en: "godparent", ja: "名付け親" },
        { en: "acquaintance", ja: "知り合い" },
        { en: "colleague", ja: "同僚" },
        { en: "classroom friend", ja: "級友" },
        { en: "best friend", ja: "親友" },
        { en: "companion", ja: "仲間" },
        { en: "individual", ja: "個人" },
        { en: "identity", ja: "アイデンティティ" },
        { en: "independent", ja: "自立した" },
        { en: "dependent", ja: "依存している" },
        { en: "mature", ja: "成熟した" },
        { en: "immature", ja: "未熟な" },
        { en: "wise", ja: "賢い" },
        { en: "stubborn", ja: "頑固な" },
        { en: "gentle", ja: "優しい" },
        { en: "strict", ja: "厳しい" },
        { en: "affectionate", ja: "愛情深い" },
        { en: "considerate", ja: "思いやりのある" },
        { en: "selfish", ja: "わがままな" },
        { en: "generous", ja: "気前の良い" },
        { en: "humble", ja: "謙虚な" },
        { en: "proud", ja: "誇りに思う" },
        { en: "ambitious", ja: "野心的な" },
        { en: "cheerful", ja: "陽気な" },
        { en: "shy", ja: "恥ずかしがりの" },
        { en: "outgoing", ja: "社交的な" }
      ]
    },
    {
      id: "daily",
      name: "Daily Routine",
      emoji: "⏰",
      level: 5,
      words: [
        { en: "wake up", ja: "起きる" },
        { en: "get up", ja: "起き上がる" },
        { en: "brush (teeth)", ja: "磨く" },
        { en: "eat", ja: "食べる" },
        { en: "drink", ja: "飲む" },
        { en: "study", ja: "勉強する" },
        { en: "play", ja: "遊ぶ" },
        { en: "sleep", ja: "眠る" },
        { en: "go home", ja: "帰宅する" },
        { en: "clean", ja: "掃除する" },
        { en: "watch", ja: "見る" },
        { en: "listen", ja: "聞く" },
        { en: "take a bath", ja: "お風呂に入る" },
        { en: "get dressed", ja: "着替える" },
        { en: "make breakfast", ja: "朝食を作る" },
        { en: "do the laundry", ja: "洗濯する" },
        { en: "take out the trash", ja: "ゴミを出す" },
        { en: "walk the dog", ja: "犬を散歩させる" },
        { en: "commute", ja: "通勤・通学する" },
        { en: "relax", ja: "くつろぐ" },
        { en: "exercise", ja: "運動する" },
        { en: "check email", ja: "メールを確認する" },
        { en: "set an alarm", ja: "目覚ましをかける" },
        { en: "lock the door", ja: "ドアに鍵をかける" },
        { en: "turn off the light", ja: "電気を消す" },
        { en: "habit", ja: "習慣" },
        { en: "routine", ja: "日課" },
        { en: "schedule (verb)", ja: "予定を立てる" },
        { en: "errand", ja: "用事" },
        { en: "chore", ja: "家事" },
        { en: "wash the dishes", ja: "皿を洗う" },
        { en: "vacuum", ja: "掃除機をかける" },
        { en: "iron clothes", ja: "アイロンをかける" },
        { en: "make the bed", ja: "ベッドを整える" },
        { en: "water the plants", ja: "植物に水をやる" },
        { en: "feed the pet", ja: "ペットに餌をやる" },
        { en: "go shopping", ja: "買い物に行く" },
        { en: "cook dinner", ja: "夕食を作る" },
        { en: "pack a lunch", ja: "弁当を詰める" },
        { en: "get ready", ja: "準備する" },
        { en: "comb hair", ja: "髪をとかす" },
        { en: "shave", ja: "ひげを剃る" },
        { en: "put on makeup", ja: "化粧をする" },
        { en: "check the time", ja: "時間を確認する" },
        { en: "hurry up", ja: "急ぐ" },
        { en: "be late", ja: "遅れる" },
        { en: "arrive on time", ja: "時間通りに着く" },
        { en: "leave home", ja: "家を出る" },
        { en: "come back", ja: "戻る" },
        { en: "rest", ja: "休む" },
        { en: "nap", ja: "昼寝する" },
        { en: "stay up late", ja: "夜更かしする" },
        { en: "go to bed", ja: "寝る" },
        { en: "fall asleep", ja: "眠りに落ちる" },
        { en: "stretch", ja: "ストレッチする" },
        { en: "yawn", ja: "あくびをする" },
        { en: "brush hair", ja: "髪をブラッシングする" },
        { en: "tidy up", ja: "片付ける" },
        { en: "organize", ja: "整理する" },
        { en: "throw away", ja: "捨てる" },
        { en: "borrow", ja: "借りる" },
        { en: "lend", ja: "貸す" },
        { en: "return (something)", ja: "返す" },
        { en: "repair", ja: "修理する" },
        { en: "fix", ja: "直す" },
        { en: "charge (a phone)", ja: "充電する" },
        { en: "plug in", ja: "プラグを差し込む" },
        { en: "unplug", ja: "プラグを抜く" },
        { en: "turn on", ja: "つける" },
        { en: "turn off", ja: "消す" },
        { en: "answer the phone", ja: "電話に出る" },
        { en: "text (message)", ja: "メッセージを送る" },
        { en: "call (someone)", ja: "電話する" },
        { en: "visit", ja: "訪ねる" },
        { en: "meet up", ja: "会う" },
        { en: "hang out", ja: "遊びに出かける" },
        { en: "stay home", ja: "家にいる" },
        { en: "spend time", ja: "時間を過ごす" },
        { en: "waste time", ja: "時間を無駄にする" },
        { en: "manage time", ja: "時間を管理する" },
        { en: "be busy", ja: "忙しい" },
        { en: "be free", ja: "暇である" },
        { en: "take a break", ja: "休憩する" },
        { en: "concentrate", ja: "集中する" },
        { en: "get distracted", ja: "気が散る" },
        { en: "finish", ja: "終える" },
        { en: "start", ja: "始める" },
        { en: "continue", ja: "続ける" },
        { en: "stop", ja: "止める" },
        { en: "prepare", ja: "準備する" },
        { en: "plan", ja: "計画する" },
        { en: "remember", ja: "覚えている" },
        { en: "forget", ja: "忘れる" },
        { en: "remind", ja: "思い出させる" }
      ]
    },
    {
      id: "food",
      name: "Food & Drink",
      emoji: "🍙",
      level: 5,
      words: [
        { en: "rice", ja: "ご飯" },
        { en: "bread", ja: "パン" },
        { en: "milk", ja: "牛乳" },
        { en: "water", ja: "水" },
        { en: "apple", ja: "りんご" },
        { en: "orange", ja: "オレンジ" },
        { en: "egg", ja: "卵" },
        { en: "fish", ja: "魚" },
        { en: "meat", ja: "肉" },
        { en: "vegetable", ja: "野菜" },
        { en: "delicious", ja: "おいしい" },
        { en: "hungry", ja: "お腹が空いた" },
        { en: "thirsty", ja: "喉が渇いた" },
        { en: "sweet", ja: "甘い" },
        { en: "salty", ja: "しょっぱい" },
        { en: "spicy", ja: "辛い" },
        { en: "sour", ja: "酸っぱい" },
        { en: "bitter", ja: "苦い" },
        { en: "recipe", ja: "レシピ" },
        { en: "ingredient", ja: "材料" },
        { en: "flavor", ja: "味" },
        { en: "menu", ja: "メニュー" },
        { en: "order (food)", ja: "注文する" },
        { en: "leftovers", ja: "残り物" },
        { en: "snack", ja: "おやつ" },
        { en: "dessert", ja: "デザート" },
        { en: "boil", ja: "ゆでる" },
        { en: "fry", ja: "揚げる・焼く" },
        { en: "bake", ja: "焼く（オーブン）" },
        { en: "chop", ja: "刻む" },
        { en: "nutritious", ja: "栄養のある" },
        { en: "diet", ja: "食事・ダイエット" },
        { en: "appetite", ja: "食欲" },
        { en: "leftover", ja: "残った" },
        { en: "vegetarian", ja: "ベジタリアン" },
        { en: "banana", ja: "バナナ" },
        { en: "strawberry", ja: "いちご" },
        { en: "grape", ja: "ぶどう" },
        { en: "watermelon", ja: "スイカ" },
        { en: "peach", ja: "桃" },
        { en: "carrot", ja: "にんじん" },
        { en: "potato", ja: "じゃがいも" },
        { en: "onion", ja: "玉ねぎ" },
        { en: "tomato", ja: "トマト" },
        { en: "cucumber", ja: "きゅうり" },
        { en: "cabbage", ja: "キャベツ" },
        { en: "corn", ja: "とうもろこし" },
        { en: "chicken (meat)", ja: "鶏肉" },
        { en: "beef", ja: "牛肉" },
        { en: "pork", ja: "豚肉" },
        { en: "shrimp", ja: "えび" },
        { en: "noodles", ja: "麺" },
        { en: "soup", ja: "スープ" },
        { en: "salad", ja: "サラダ" },
        { en: "sandwich", ja: "サンドイッチ" },
        { en: "curry", ja: "カレー" },
        { en: "sushi", ja: "寿司" },
        { en: "cake", ja: "ケーキ" },
        { en: "cookie", ja: "クッキー" },
        { en: "ice cream", ja: "アイスクリーム" },
        { en: "chocolate", ja: "チョコレート" },
        { en: "candy", ja: "キャンディー" },
        { en: "juice", ja: "ジュース" },
        { en: "tea", ja: "お茶" },
        { en: "coffee", ja: "コーヒー" },
        { en: "soda", ja: "炭酸飲料" },
        { en: "sugar", ja: "砂糖" },
        { en: "salt", ja: "塩" },
        { en: "pepper", ja: "こしょう" },
        { en: "oil", ja: "油" },
        { en: "butter", ja: "バター" },
        { en: "cheese", ja: "チーズ" },
        { en: "yogurt", ja: "ヨーグルト" },
        { en: "sauce", ja: "ソース" },
        { en: "soy sauce", ja: "醤油" },
        { en: "chopsticks", ja: "箸" },
        { en: "fork", ja: "フォーク" },
        { en: "spoon", ja: "スプーン" },
        { en: "knife", ja: "ナイフ" },
        { en: "plate", ja: "皿" },
        { en: "bowl", ja: "ボウル" },
        { en: "cup", ja: "コップ" },
        { en: "napkin", ja: "ナプキン" },
        { en: "portion", ja: "一人前" },
        { en: "serving", ja: "一人前" },
        { en: "calorie", ja: "カロリー" },
        { en: "fat (nutrient)", ja: "脂肪" },
        { en: "protein", ja: "たんぱく質" },
        { en: "carbohydrate", ja: "炭水化物" },
        { en: "vitamin", ja: "ビタミン" },
        { en: "fresh", ja: "新鮮な" },
        { en: "rotten", ja: "腐った" },
        { en: "raw", ja: "生の" },
        { en: "frozen", ja: "冷凍の" },
        { en: "canned", ja: "缶詰の" },
        { en: "homemade", ja: "手作りの" },
        { en: "organic", ja: "有機の" },
        { en: "allergy (food)", ja: "アレルギー" },
        { en: "expiration date", ja: "賞味期限" }
      ]
    },
    {
      id: "town",
      name: "Town & Places",
      emoji: "🏙️",
      level: 4,
      words: [
        { en: "station", ja: "駅" },
        { en: "hospital", ja: "病院" },
        { en: "park", ja: "公園" },
        { en: "supermarket", ja: "スーパー" },
        { en: "restaurant", ja: "レストラン" },
        { en: "bookstore", ja: "本屋" },
        { en: "post office", ja: "郵便局" },
        { en: "bank", ja: "銀行" },
        { en: "museum", ja: "博物館" },
        { en: "convenience store", ja: "コンビニ" },
        { en: "city hall", ja: "市役所" },
        { en: "police station", ja: "警察署" },
        { en: "fire station", ja: "消防署" },
        { en: "airport", ja: "空港" },
        { en: "harbor", ja: "港" },
        { en: "bridge", ja: "橋" },
        { en: "intersection", ja: "交差点" },
        { en: "sidewalk", ja: "歩道" },
        { en: "crosswalk", ja: "横断歩道" },
        { en: "neighborhood", ja: "近所" },
        { en: "suburb", ja: "郊外" },
        { en: "downtown", ja: "繁華街" },
        { en: "factory", ja: "工場" },
        { en: "construction site", ja: "建設現場" },
        { en: "apartment building", ja: "マンション" },
        { en: "shopping mall", ja: "ショッピングモール" },
        { en: "parking lot", ja: "駐車場" },
        { en: "gas station", ja: "ガソリンスタンド" },
        { en: "temple", ja: "寺" },
        { en: "shrine", ja: "神社" },
        { en: "skyscraper", ja: "高層ビル" },
        { en: "population", ja: "人口" },
        { en: "facility", ja: "施設" },
        { en: "landmark", ja: "目印・名所" },
        { en: "town hall", ja: "町役場" },
        { en: "courthouse", ja: "裁判所" },
        { en: "embassy", ja: "大使館" },
        { en: "church", ja: "教会" },
        { en: "stadium", ja: "競技場" },
        { en: "gymnasium", ja: "体育館" },
        { en: "zoo", ja: "動物園" },
        { en: "aquarium", ja: "水族館" },
        { en: "amusement park", ja: "遊園地" },
        { en: "theater", ja: "劇場" },
        { en: "movie theater", ja: "映画館" },
        { en: "art gallery", ja: "美術館" },
        { en: "community center", ja: "公民館" },
        { en: "town square", ja: "広場" },
        { en: "fountain", ja: "噴水" },
        { en: "statue", ja: "像" },
        { en: "monument", ja: "記念碑" },
        { en: "cemetery", ja: "墓地" },
        { en: "farm", ja: "農場" },
        { en: "field", ja: "畑・野原" },
        { en: "forest", ja: "森" },
        { en: "mountain", ja: "山" },
        { en: "river", ja: "川" },
        { en: "lake", ja: "湖" },
        { en: "beach", ja: "ビーチ" },
        { en: "coast", ja: "海岸" },
        { en: "island", ja: "島" },
        { en: "valley", ja: "谷" },
        { en: "hill", ja: "丘" },
        { en: "road", ja: "道路" },
        { en: "street", ja: "通り" },
        { en: "avenue", ja: "大通り" },
        { en: "alley", ja: "路地" },
        { en: "block (city)", ja: "街区" },
        { en: "corner", ja: "角" },
        { en: "address", ja: "住所" },
        { en: "map", ja: "地図" },
        { en: "direction", ja: "方向" },
        { en: "distance", ja: "距離" },
        { en: "nearby", ja: "近くの" },
        { en: "far", ja: "遠い" },
        { en: "located", ja: "位置している" },
        { en: "urban", ja: "都市の" },
        { en: "rural", ja: "田舎の" },
        { en: "crowded", ja: "混雑した" },
        { en: "quiet (place)", ja: "静かな" },
        { en: "noisy", ja: "うるさい" },
        { en: "safe", ja: "安全な" },
        { en: "dangerous", ja: "危険な" },
        { en: "clean (place)", ja: "清潔な" },
        { en: "dirty", ja: "汚い" },
        { en: "modern", ja: "現代的な" },
        { en: "historic", ja: "歴史的な" },
        { en: "famous", ja: "有名な" },
        { en: "local", ja: "地元の" },
        { en: "resident", ja: "住民" },
        { en: "citizen", ja: "市民" },
        { en: "mayor", ja: "市長" },
        { en: "construction", ja: "建設" },
        { en: "renovation", ja: "改修" },
        { en: "development", ja: "開発" },
        { en: "infrastructure", ja: "インフラ" },
        { en: "sewer", ja: "下水道" },
        { en: "streetlight", ja: "街灯" },
        { en: "billboard", ja: "看板" },
        { en: "sign", ja: "標識" }
      ]
    },
    {
      id: "hobbies",
      name: "Hobbies & Sports",
      emoji: "⚽",
      level: 4,
      words: [
        { en: "soccer", ja: "サッカー" },
        { en: "baseball", ja: "野球" },
        { en: "basketball", ja: "バスケットボール" },
        { en: "tennis", ja: "テニス" },
        { en: "swimming", ja: "水泳" },
        { en: "drawing", ja: "絵を描くこと" },
        { en: "reading", ja: "読書" },
        { en: "singing", ja: "歌うこと" },
        { en: "dancing", ja: "踊ること" },
        { en: "guitar", ja: "ギター" },
        { en: "piano", ja: "ピアノ" },
        { en: "photography", ja: "写真撮影" },
        { en: "cooking", ja: "料理" },
        { en: "gardening", ja: "ガーデニング" },
        { en: "fishing", ja: "釣り" },
        { en: "camping", ja: "キャンプ" },
        { en: "hiking", ja: "ハイキング" },
        { en: "cycling", ja: "サイクリング" },
        { en: "skating", ja: "スケート" },
        { en: "skiing", ja: "スキー" },
        { en: "volleyball", ja: "バレーボール" },
        { en: "badminton", ja: "バドミントン" },
        { en: "table tennis", ja: "卓球" },
        { en: "martial arts", ja: "武道" },
        { en: "team", ja: "チーム" },
        { en: "coach", ja: "コーチ" },
        { en: "competition", ja: "大会" },
        { en: "champion", ja: "チャンピオン" },
        { en: "practice (noun)", ja: "練習" },
        { en: "skill", ja: "技術" },
        { en: "talent", ja: "才能" },
        { en: "instrument", ja: "楽器" },
        { en: "collect", ja: "集める" },
        { en: "puzzle", ja: "パズル" }
      ]
    },
    {
      id: "weather-time",
      name: "Weather & Time",
      emoji: "☀️",
      level: 4,
      words: [
        { en: "sunny", ja: "晴れの" },
        { en: "rainy", ja: "雨の" },
        { en: "cloudy", ja: "曇りの" },
        { en: "snowy", ja: "雪の" },
        { en: "windy", ja: "風が強い" },
        { en: "today", ja: "今日" },
        { en: "tomorrow", ja: "明日" },
        { en: "yesterday", ja: "昨日" },
        { en: "morning", ja: "朝" },
        { en: "evening", ja: "夕方" },
        { en: "humid", ja: "湿気の多い" },
        { en: "foggy", ja: "霧の" },
        { en: "thunderstorm", ja: "雷雨" },
        { en: "temperature", ja: "気温" },
        { en: "forecast", ja: "予報" },
        { en: "season", ja: "季節" },
        { en: "spring", ja: "春" },
        { en: "summer", ja: "夏" },
        { en: "autumn", ja: "秋" },
        { en: "winter", ja: "冬" },
        { en: "century", ja: "世紀" },
        { en: "decade", ja: "10年間" },
        { en: "anniversary", ja: "記念日" },
        { en: "deadline", ja: "締め切り" },
        { en: "punctual", ja: "時間を守る" },
        { en: "in advance", ja: "前もって" },
        { en: "eventually", ja: "結局" },
        { en: "recently", ja: "最近" },
        { en: "frequently", ja: "頻繁に" },
        { en: "occasionally", ja: "時々" }
      ]
    },
    {
      id: "travel",
      name: "Travel & Transportation",
      emoji: "✈️",
      level: 3,
      words: [
        { en: "passport", ja: "パスポート" },
        { en: "luggage", ja: "荷物" },
        { en: "ticket", ja: "切符・チケット" },
        { en: "reservation", ja: "予約" },
        { en: "destination", ja: "目的地" },
        { en: "departure", ja: "出発" },
        { en: "arrival", ja: "到着" },
        { en: "delay", ja: "遅延" },
        { en: "platform", ja: "プラットホーム" },
        { en: "boarding pass", ja: "搭乗券" },
        { en: "customs", ja: "税関" },
        { en: "tour guide", ja: "ツアーガイド" },
        { en: "sightseeing", ja: "観光" },
        { en: "souvenir", ja: "お土産" },
        { en: "currency", ja: "通貨" },
        { en: "exchange rate", ja: "為替レート" },
        { en: "itinerary", ja: "旅程" },
        { en: "accommodation", ja: "宿泊施設" },
        { en: "highway", ja: "高速道路" },
        { en: "traffic jam", ja: "交通渋滞" },
        { en: "subway", ja: "地下鉄" },
        { en: "ferry", ja: "フェリー" },
        { en: "round trip", ja: "往復" },
        { en: "one-way", ja: "片道" },
        { en: "transfer (trains)", ja: "乗り換え" },
        { en: "abroad", ja: "海外で" },
        { en: "foreign", ja: "外国の" },
        { en: "culture", ja: "文化" },
        { en: "tradition", ja: "伝統" },
        { en: "explore", ja: "探検する" }
      ]
    },
    {
      id: "society",
      name: "Society & Environment",
      emoji: "🌍",
      level: 3,
      words: [
        { en: "environment", ja: "環境" },
        { en: "pollution", ja: "汚染" },
        { en: "recycle", ja: "リサイクルする" },
        { en: "resource", ja: "資源" },
        { en: "energy", ja: "エネルギー" },
        { en: "climate", ja: "気候" },
        { en: "global warming", ja: "地球温暖化" },
        { en: "endangered", ja: "絶滅の危機にある" },
        { en: "wildlife", ja: "野生動物" },
        { en: "ecosystem", ja: "生態系" },
        { en: "government", ja: "政府" },
        { en: "election", ja: "選挙" },
        { en: "economy", ja: "経済" },
        { en: "industry", ja: "産業" },
        { en: "technology", ja: "技術" },
        { en: "invention", ja: "発明" },
        { en: "communication", ja: "コミュニケーション" },
        { en: "community", ja: "地域社会" },
        { en: "volunteer", ja: "ボランティア" },
        { en: "charity", ja: "慈善事業" },
        { en: "responsibility", ja: "責任" },
        { en: "opportunity", ja: "機会" },
        { en: "challenge", ja: "課題・挑戦" },
        { en: "solution", ja: "解決策" },
        { en: "issue", ja: "問題" },
        { en: "policy", ja: "政策" },
        { en: "law", ja: "法律" },
        { en: "tax", ja: "税金" },
        { en: "income", ja: "収入" },
        { en: "poverty", ja: "貧困" }
      ]
    }
  ];

  // ---- Sentence-pattern questions (word-order builder) ----
  // tokens: words in CORRECT order. The game will shuffle them for the student.
  // "level" roughly maps to Eiken levels: 5 (easiest) -> 4 -> 3 -> pre2 -> 2.
  var SENTENCES = [
    // --- Eiken 5 (simple present/past, basic questions) ---
    { level: 5, tokens: ["I", "am", "a", "student", "."], ja: "私は学生です。" },
    { level: 5, tokens: ["She", "is", "my", "sister", "."], ja: "彼女は私の姉です。" },
    { level: 5, tokens: ["I", "eat", "breakfast", "every", "day", "."], ja: "私は毎日朝食を食べます。" },
    { level: 5, tokens: ["He", "plays", "soccer", "on", "Sunday", "."], ja: "彼は日曜日にサッカーをします。" },
    { level: 5, tokens: ["Do", "you", "like", "music", "?"], ja: "あなたは音楽が好きですか。" },
    { level: 5, tokens: ["What", "time", "is", "it", "?"], ja: "今何時ですか。" },
    { level: 5, tokens: ["This", "is", "my", "pencil", "."], ja: "これは私の鉛筆です。" },
    { level: 5, tokens: ["I", "am", "studying", "English", "now", "."], ja: "私は今英語を勉強しています。" },

    // --- Eiken 4 (past tense, simple negatives, want to / can) ---
    { level: 4, tokens: ["I", "went", "to", "school", "yesterday", "."], ja: "私は昨日学校に行きました。" },
    { level: 4, tokens: ["She", "did", "not", "eat", "lunch", "."], ja: "彼女は昼食を食べませんでした。" },
    { level: 4, tokens: ["Where", "is", "the", "station", "?"], ja: "駅はどこですか。" },
    { level: 4, tokens: ["I", "want", "to", "be", "a", "teacher", "."], ja: "私は先生になりたいです。" },
    { level: 4, tokens: ["He", "was", "playing", "tennis", "."], ja: "彼はテニスをしていました。" },
    { level: 4, tokens: ["Can", "you", "help", "me", "?"], ja: "手伝ってくれますか。" },

    // --- Eiken 3 (conjunctions: because, when, if, after, before) ---
    { level: 3, tokens: ["I", "was", "happy", "because", "I", "passed", "the", "test", "."], ja: "テストに合格したので、私はうれしかったです。" },
    { level: 3, tokens: ["When", "I", "got", "home", ",", "it", "was", "raining", "."], ja: "私が家に着いたとき、雨が降っていました。" },
    { level: 3, tokens: ["If", "it", "rains", "tomorrow", ",", "we", "will", "stay", "home", "."], ja: "もし明日雨が降ったら、私たちは家にいます。" },
    { level: 3, tokens: ["After", "I", "finish", "my", "homework", ",", "I", "will", "watch", "TV", "."], ja: "宿題を終えた後、テレビを見ます。" },
    { level: 3, tokens: ["Before", "you", "go", "out", ",", "please", "lock", "the", "door", "."], ja: "外出する前に、ドアに鍵をかけてください。" },
    { level: 3, tokens: ["She", "studies", "hard", "so", "that", "she", "can", "pass", "the", "exam", "."], ja: "彼女は試験に合格できるように一生懸命勉強します。" },
    { level: 3, tokens: ["I", "have", "lived", "here", "since", "I", "was", "a", "child", "."], ja: "私は子どもの頃からここに住んでいます。" },
    { level: 3, tokens: ["He", "is", "too", "tired", "to", "walk", "any", "farther", "."], ja: "彼は疲れすぎてこれ以上歩けません。" },

    // --- Eiken Pre-2 / 2 (relative clauses, passive voice, comparisons, although) ---
    { level: 2, tokens: ["The", "book", "that", "I", "bought", "yesterday", "is", "very", "interesting", "."], ja: "私が昨日買った本はとても面白いです。" },
    { level: 2, tokens: ["Although", "it", "was", "raining", ",", "we", "decided", "to", "go", "out", "."], ja: "雨が降っていましたが、私たちは外出することにしました。" },
    { level: 2, tokens: ["This", "house", "was", "built", "by", "my", "grandfather", "."], ja: "この家は私の祖父によって建てられました。" },
    { level: 2, tokens: ["The", "more", "you", "practice", ",", "the", "better", "you", "become", "."], ja: "練習すればするほど、上手になります。" },
    { level: 2, tokens: ["She", "is", "the", "kindest", "person", "that", "I", "have", "ever", "met", "."], ja: "彼女は私が今まで会った中で最も優しい人です。" },
    { level: 2, tokens: ["Unless", "you", "hurry", "up", ",", "you", "will", "miss", "the", "train", "."], ja: "急がない限り、電車に乗り遅れますよ。" },
    { level: 2, tokens: ["I", "wonder", "if", "he", "will", "come", "to", "the", "party", "."], ja: "彼がパーティーに来るかどうか気になります。" },
    { level: 2, tokens: ["By", "the", "time", "we", "arrived", ",", "the", "concert", "had", "already", "started", "."], ja: "私たちが到着するまでに、コンサートはすでに始まっていました。" },
    { level: 2, tokens: ["It", "is", "important", "for", "students", "to", "manage", "their", "time", "well", "."], ja: "生徒にとって時間をうまく管理することが大切です。" },
    { level: 2, tokens: ["Not", "only", "did", "she", "win", "the", "race", ",", "but", "she", "also", "broke", "the", "record", "."], ja: "彼女はレースに勝っただけでなく、記録も更新しました。" }
  ];

  global.EQ_CONTENT = { UNITS: UNITS, SENTENCES: SENTENCES };
})(window);
